# Generated by Django 5.1.15 on 2026-07-26 18:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_operation_id', models.UUIDField(db_index=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255)),
                ('operation_type', models.CharField(max_length=50)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payload_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('received', 'مستلم'), ('processing', 'قيد المعالجة'), ('completed', 'مكتمل'), ('failed', 'فاشل'), ('conflicted', 'تعارض')], db_index=True, default='received', max_length=20)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.studyenrollment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عملية مزامنة',
                'verbose_name_plural': 'عمليات المزامنة',
                'db_table': 'synchronization_operations',
                'ordering': ['-created_at'],
            },
        ),
    ]
