# Generated by Django 5.1.15 on 2026-07-29 02:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_phoneverification_verification_grant_hash_and_more'),
        ('curriculum', '0003_alter_unit_term'),
        ('synchronization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncBatchReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_batch_id', models.UUIDField(db_index=True)),
                ('payload_hash', models.CharField(db_index=True, max_length=64)),
                ('operations_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('received', 'مستلم'), ('processing', 'قيد المعالجة'), ('completed', 'مكتمل'), ('failed', 'فاشل'), ('conflict', 'تعارض'), ('conflicted', 'تعارض'), ('unsupported', 'غير مدعوم')], db_index=True, default='received', max_length=20)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إيصال دفعة مزامنة',
                'verbose_name_plural': 'إيصالات دفعات المزامنة',
                'db_table': 'synchronization_batch_receipts',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncChange',
            fields=[
                ('sequence', models.BigAutoField(primary_key=True, serialize=False)),
                ('resource_type', models.CharField(db_index=True, max_length=50)),
                ('resource_id', models.CharField(db_index=True, max_length=255)),
                ('action', models.CharField(choices=[('upsert', 'تحديث/إضافة'), ('delete', 'حذف'), ('archive', 'أرشفة'), ('restore', 'استعادة'), ('access_revoked', 'إلغاء الوصول')], db_index=True, default='upsert', max_length=20)),
                ('resource_version', models.CharField(default='1', max_length=50)),
                ('metadata_snapshot', models.JSONField(blank=True, default=dict)),
                ('changed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تغيير مزامنة',
                'verbose_name_plural': 'تغييرات المزامنة',
                'db_table': 'synchronization_changes',
                'ordering': ['sequence'],
            },
        ),
        migrations.AddField(
            model_name='syncoperation',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_operations', to='accounts.userdevice'),
        ),
        migrations.AddField(
            model_name='syncoperation',
            name='normalized_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncoperation',
            name='occurred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncoperation',
            name='processing_version',
            field=models.CharField(default='v1', max_length=50),
        ),
        migrations.AddField(
            model_name='syncoperation',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='syncoperation',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='syncoperation',
            name='entity_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='syncoperation',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='syncoperation',
            name='operation_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='syncoperation',
            name='payload_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='syncoperation',
            name='status',
            field=models.CharField(choices=[('received', 'مستلم'), ('processing', 'قيد المعالجة'), ('completed', 'مكتمل'), ('failed', 'فاشل'), ('conflict', 'تعارض'), ('conflicted', 'تعارض'), ('unsupported', 'غير مدعوم')], db_index=True, default='received', max_length=20),
        ),
        migrations.AlterField(
            model_name='syncoperation',
            name='study_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.studyenrollment'),
        ),
        migrations.AddConstraint(
            model_name='syncoperation',
            constraint=models.UniqueConstraint(fields=('user', 'installation', 'client_operation_id'), name='unique_sync_operation_per_installation'),
        ),
        migrations.AddField(
            model_name='syncbatchreceipt',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_batch_receipts', to='accounts.userdevice'),
        ),
        migrations.AddField(
            model_name='syncbatchreceipt',
            name='study_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.studyenrollment'),
        ),
        migrations.AddField(
            model_name='syncbatchreceipt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_batch_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syncchange',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_changes', to='curriculum.grade'),
        ),
        migrations.AddField(
            model_name='syncchange',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_changes', to='curriculum.lesson'),
        ),
        migrations.AddField(
            model_name='syncchange',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_changes', to='curriculum.section'),
        ),
        migrations.AddField(
            model_name='syncchange',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_changes', to='curriculum.subject'),
        ),
        migrations.AddField(
            model_name='syncchange',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_changes', to='curriculum.unit'),
        ),
        migrations.AddConstraint(
            model_name='syncbatchreceipt',
            constraint=models.UniqueConstraint(fields=('user', 'installation', 'client_batch_id'), name='unique_sync_batch_per_installation'),
        ),
        migrations.AddIndex(
            model_name='syncchange',
            index=models.Index(fields=['sequence', 'resource_type'], name='synchroniza_sequenc_941f48_idx'),
        ),
        migrations.AddIndex(
            model_name='syncchange',
            index=models.Index(fields=['resource_type', 'resource_id'], name='synchroniza_resourc_2bb16d_idx'),
        ),
        migrations.AddIndex(
            model_name='syncchange',
            index=models.Index(fields=['changed_at'], name='synchroniza_changed_826fd7_idx'),
        ),
    ]
