# Generated by Django 5.1.15 on 2026-07-26 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'لم يبدأ'), ('in_progress', 'قيد التقدم'), ('completed', 'مكتمل'), ('mastered', 'متمكن'), ('needs_review', 'يحتاج مراجعة')], db_index=True, default='not_started', max_length=20)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('best_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('total_answers', models.PositiveIntegerField(default=0)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('mastered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.lesson')),
                ('study_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.studyenrollment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تقدم الدرس',
                'verbose_name_plural': 'تقدم الدروس',
                'db_table': 'progress_lesson_progresses',
                'unique_together': {('user', 'study_enrollment', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='SubjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'لم يبدأ'), ('in_progress', 'قيد التقدم'), ('completed', 'مكتمل'), ('mastered', 'متمكن'), ('needs_review', 'يحتاج مراجعة')], db_index=True, default='not_started', max_length=20)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('units_completed', models.PositiveIntegerField(default=0)),
                ('units_total', models.PositiveIntegerField(default=0)),
                ('average_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.studyenrollment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تقدم المادة',
                'verbose_name_plural': 'تقدم المواد',
                'db_table': 'progress_subject_progresses',
                'unique_together': {('user', 'study_enrollment', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='UnitProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'لم يبدأ'), ('in_progress', 'قيد التقدم'), ('completed', 'مكتمل'), ('mastered', 'متمكن'), ('needs_review', 'يحتاج مراجعة')], db_index=True, default='not_started', max_length=20)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('lessons_completed', models.PositiveIntegerField(default=0)),
                ('lessons_total', models.PositiveIntegerField(default=0)),
                ('best_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.studyenrollment')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تقدم الوحدة',
                'verbose_name_plural': 'تقدم الوحدات',
                'db_table': 'progress_unit_progresses',
                'unique_together': {('user', 'study_enrollment', 'unit')},
            },
        ),
    ]
