# Generated by Django 5.1.15 on 2026-07-28 22:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0002_alter_attemptanswer_unique_together_and_more'),
        ('curriculum', '0003_alter_unit_term'),
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptProgressReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress_version', models.IntegerField(default=1)),
                ('analytics_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إيصال تقدم المحاولة',
                'verbose_name_plural': 'إيصالات تقدم المحاولات',
                'db_table': 'progress_attempt_receipts',
            },
        ),
        migrations.CreateModel(
            name='LearningResourceProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(db_index=True, max_length=50)),
                ('resource_id', models.CharField(db_index=True, max_length=200)),
                ('status', models.CharField(choices=[('not_started', 'لم يبدأ'), ('in_progress', 'قيد التقدم'), ('completed', 'مكتمل'), ('mastered', 'متمكن'), ('needs_review', 'يحتاج مراجعة')], db_index=True, default='not_started', max_length=20)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('resource_snapshot', models.JSONField(blank=True, default=dict)),
                ('source_version', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تقدم المورد التعليمي',
                'verbose_name_plural': 'تقدم الموارد التعليمية',
                'db_table': 'progress_learning_resource_progresses',
            },
        ),
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_session_id', models.CharField(db_index=True, max_length=255)),
                ('resource_type', models.CharField(blank=True, default='', max_length=50)),
                ('resource_id', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('active', 'نشط'), ('completed', 'مكتمل'), ('abandoned', 'مهجور'), ('expired', 'منتهي')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_heartbeat_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'جلسة التعلم',
                'verbose_name_plural': 'جلسات التعلم',
                'db_table': 'progress_learning_sessions',
            },
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subjectprogress',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='unitprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='average_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='latest_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='mastery_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subjectprogress',
            name='attempts_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subjectprogress',
            name='best_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='subjectprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectprogress',
            name='latest_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='subjectprogress',
            name='mastery_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='subjectprogress',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unitprogress',
            name='attempts_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unitprogress',
            name='average_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='unitprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unitprogress',
            name='latest_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='unitprogress',
            name='mastery_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='unitprogress',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='lessonprogress',
            constraint=models.UniqueConstraint(fields=('user', 'study_enrollment', 'lesson'), name='unique_lesson_progress_per_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='subjectprogress',
            constraint=models.UniqueConstraint(fields=('user', 'study_enrollment', 'subject'), name='unique_subject_progress_per_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='unitprogress',
            constraint=models.UniqueConstraint(fields=('user', 'study_enrollment', 'unit'), name='unique_unit_progress_per_enrollment'),
        ),
        migrations.AddField(
            model_name='attemptprogressreceipt',
            name='attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress_receipt', to='attempts.assessmentattempt'),
        ),
        migrations.AddField(
            model_name='learningresourceprogress',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.lesson'),
        ),
        migrations.AddField(
            model_name='learningresourceprogress',
            name='study_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.studyenrollment'),
        ),
        migrations.AddField(
            model_name='learningresourceprogress',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.subject'),
        ),
        migrations.AddField(
            model_name='learningresourceprogress',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.unit'),
        ),
        migrations.AddField(
            model_name='learningresourceprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_resource_progresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.lesson'),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='study_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.studyenrollment'),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.subject'),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.unit'),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='correct_answers',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='total_answers',
        ),
        migrations.AddConstraint(
            model_name='learningresourceprogress',
            constraint=models.UniqueConstraint(fields=('user', 'study_enrollment', 'resource_type', 'resource_id'), name='unique_resource_progress_per_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='learningsession',
            constraint=models.UniqueConstraint(fields=('user', 'client_session_id'), name='unique_learning_session_per_user'),
        ),
    ]
