# Generated by Django 5.1.15 on 2026-07-24 01:54

import apps.accounts.models.user
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_code', models.CharField(default=apps.accounts.models.user.generate_public_code, help_text='رمز عام قصير للعرض والدعم الفني.', max_length=20, unique=True)),
                ('account_type', models.CharField(choices=[('guest', 'زائر'), ('registered', 'مسجل')], db_index=True, default='guest', max_length=12)),
                ('phone', models.CharField(blank=True, db_index=True, help_text='رقم الهاتف بصيغة يمنية (+9677XXXXXXXX). فارغ للزائر.', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يكون بصيغة +9677XXXXXXXX', regex='^\\+9677\\d{8}$')])),
                ('phone_verified_at', models.DateTimeField(blank=True, help_text='وقت التحقق من رقم الهاتف.', null=True)),
                ('upgraded_at', models.DateTimeField(blank=True, help_text='وقت تحويل الزائر إلى مستخدم مسجل.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
                'db_table': 'accounts_user',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountMerge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'قيد المعالجة'), ('completed', 'مكتمل'), ('failed', 'فاشل')], db_index=True, default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('conflict_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merges_as_source', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merges_as_target', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دمج الحساب',
                'verbose_name_plural': 'عمليات دمج الحسابات',
                'db_table': 'accounts_account_merge',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('purpose', models.CharField(choices=[('register', 'تسجيل حساب'), ('login', 'تسجيل دخول'), ('change_phone', 'تغيير رقم الهاتف'), ('recover_account', 'استعادة الحساب')], db_index=True, max_length=20)),
                ('code_hash', models.CharField(help_text='Hashed OTP code. Never store plaintext.', max_length=255)),
                ('request_id', models.UUIDField(default=uuid.uuid4, help_text='Unique identifier for this OTP request, returned to client.', unique=True)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('resend_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sent_at', models.DateTimeField(auto_now_add=True)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('installation_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'التحقق من الهاتف',
                'verbose_name_plural': 'طلبات التحقق من الهاتف',
                'db_table': 'accounts_phone_verification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'purpose', 'expires_at'], name='accounts_ph_phone_328df8_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installation_id', models.CharField(db_index=True, help_text='Unique device identifier generated by Flutter.', max_length=255)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=10)),
                ('device_name', models.CharField(blank=True, default='', max_length=255)),
                ('operating_system', models.CharField(blank=True, default='', max_length=100)),
                ('app_version', models.CharField(blank=True, default='', max_length=20)),
                ('push_token', models.TextField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'جهاز المستخدم',
                'verbose_name_plural': 'أجهزة المستخدمين',
                'db_table': 'accounts_user_device',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refresh_token_jti', models.CharField(db_index=True, help_text='JTI claim from the refresh token.', max_length=255, unique=True)),
                ('refresh_token_hash', models.CharField(help_text='SHA-256 hash of the refresh token.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.userdevice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'جلسة المستخدم',
                'verbose_name_plural': 'جلسات المستخدمين',
                'db_table': 'accounts_user_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('phone__isnull', False)), fields=('phone',), name='unique_phone_when_not_null'),
        ),
        migrations.AddConstraint(
            model_name='userdevice',
            constraint=models.UniqueConstraint(fields=('user', 'installation_id'), name='unique_user_installation'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'device', 'expires_at', 'revoked_at'], name='accounts_us_user_id_bbfd99_idx'),
        ),
    ]
