# Generated by Django 5.1.15 on 2026-07-27 17:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneverification',
            name='verification_grant_hash',
            field=models.CharField(blank=True, help_text='HMAC-SHA256 hash of verification grant token. Set after successful OTP verify.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='code_hash',
            field=models.CharField(help_text='HMAC-SHA256 hash of OTP code. Never store plaintext.', max_length=255),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='الاسم الكامل للطالب.', max_length=255)),
                ('custom_school_name', models.CharField(blank=True, default='', help_text='اسم مدرسة مخصص إذا لم تكن موجودة في القائمة.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(blank=True, help_text='المديرية.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='locations.district')),
                ('governorate', models.ForeignKey(blank=True, help_text='المحافظة.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='locations.governorate')),
                ('isolation', models.ForeignKey(blank=True, help_text='العزلة.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='locations.isolation')),
                ('school', models.ForeignKey(blank=True, help_text='المدرسة.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='locations.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف الطالب',
                'verbose_name_plural': 'ملفات الطلاب',
                'db_table': 'accounts_student_profile',
            },
        ),
    ]
