# Generated by Django 5.1.15 on 2026-07-31 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_phoneverification_verification_grant_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverification',
            name='purpose',
            field=models.CharField(choices=[('register', 'تسجيل حساب'), ('login', 'تسجيل دخول'), ('change_phone', 'تغيير رقم الهاتف'), ('recover_account', 'استعادة الحساب'), ('reset_password', 'إعادة تعيين كلمة المرور')], db_index=True, max_length=20),
        ),
    ]
