# Generated by Django 5.1.15 on 2026-09-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentprofile_custom_locations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-created_at'], 'permissions': [('revoke_usersession', 'Can revoke active user sessions')], 'verbose_name': 'جلسة المستخدم', 'verbose_name_plural': 'جلسات المستخدمين'},
        ),
    ]
