from django.urls import path
from apps.attempts.api.views import (
    StartAssessmentAttemptAPIView,
    AttemptDetailAPIView,
    AttemptQuestionsAPIView,
    AttemptSaveAnswerAPIView,
    AttemptSubmitAPIView,
    AttemptResultAPIView,
    AttemptReviewAPIView,
    AttemptRetryWrongAPIView,
    AttemptRetryAPIView,
    MyAttemptsListAPIView,
    AssessmentEntryAPIView,
    StartAssessmentSourceAPIView,
    SubjectTrainingBatchesAPIView,
    CustomTestConfigurationAPIView,
    CustomTestPreviewAPIView,
    CustomTestCreateAPIView,
    CustomTestNewSameSettingsAPIView,
    MockBlueprintListAPIView,
    MockBlueprintDetailAPIView,
    MockBlueprintStartAPIView,
    WrongAnswerSummaryAPIView,
    WrongPracticeCreateAPIView,
    WeaknessSummaryAPIView,
    WeaknessPracticeCreateAPIView,
)

app_name = "attempts"

urlpatterns = [
    path("practice/wrong-answers/", WrongAnswerSummaryAPIView.as_view(), name="wrong-answer-summary"),
    path("practice/wrong-answers/create/", WrongPracticeCreateAPIView.as_view(), name="wrong-practice-create"),
    path("practice/weaknesses/", WeaknessSummaryAPIView.as_view(), name="weakness-summary"),
    path("practice/weaknesses/create/", WeaknessPracticeCreateAPIView.as_view(), name="weakness-practice-create"),
    path("mock-blueprints/", MockBlueprintListAPIView.as_view(), name="mock-blueprint-list"),
    path("mock-blueprints/<uuid:blueprint_id>/", MockBlueprintDetailAPIView.as_view(), name="mock-blueprint-detail"),
    path("mock-blueprints/<uuid:blueprint_id>/start/", MockBlueprintStartAPIView.as_view(), name="mock-blueprint-start"),
    path("custom-tests/configuration/", CustomTestConfigurationAPIView.as_view(), name="custom-test-configuration"),
    path("custom-tests/preview/", CustomTestPreviewAPIView.as_view(), name="custom-test-preview"),
    path("custom-tests/create/", CustomTestCreateAPIView.as_view(), name="custom-test-create"),
    path("assessment-sources/subject_training/<str:source_id>/batches/", SubjectTrainingBatchesAPIView.as_view(), name="subject-training-batches"),
    path("assessment-sources/<str:source_kind>/<str:source_id>/entry/", AssessmentEntryAPIView.as_view(), name="assessment-entry"),
    path("assessment-sources/<str:source_kind>/<str:source_id>/start/", StartAssessmentSourceAPIView.as_view(), name="assessment-source-start"),
    path("assessments/<uuid:assessment_id>/start/", StartAssessmentAttemptAPIView.as_view(), name="attempt-start"),
    path("attempts/<uuid:pk>/", AttemptDetailAPIView.as_view(), name="attempt-detail"),
    path("attempts/<uuid:pk>/questions/", AttemptQuestionsAPIView.as_view(), name="attempt-questions"),
    path("attempts/<uuid:pk>/answers/", AttemptSaveAnswerAPIView.as_view(), name="attempt-save-answer"),
    path("attempts/<uuid:pk>/submit/", AttemptSubmitAPIView.as_view(), name="attempt-submit"),
    path("attempts/<uuid:pk>/result/", AttemptResultAPIView.as_view(), name="attempt-result"),
    path("attempts/<uuid:pk>/review/", AttemptReviewAPIView.as_view(), name="attempt-review"),
    path("attempts/<uuid:pk>/retry/", AttemptRetryAPIView.as_view(), name="attempt-retry"),
    path("attempts/<uuid:pk>/new-with-same-settings/", CustomTestNewSameSettingsAPIView.as_view(), name="custom-test-new-same-settings"),
    path("attempts/<uuid:pk>/retry-wrong/", AttemptRetryWrongAPIView.as_view(), name="attempt-retry-wrong"),
    path("me/attempts/", MyAttemptsListAPIView.as_view(), name="my-attempts"),
]
