"""
URL routing for the Operations Console (/control/).
"""

from django.urls import path
from apps.control.views import (
    ControlLoginView,
    ControlLogoutView,
    DashboardView,
    ContentHomeView,
    SubjectWorkspaceView,
    UnitWorkspaceView,
    LessonWorkspaceView,
    SummaryCreateView,
    SummaryUpdateView,
    SummaryPreviewView,
    SummaryStatusToggleView,
    LessonExplanationEditView,
    LessonExplanationPreviewView,
    FlashcardDeckCreateView,
    FlashcardDeckUpdateView,
    FlashcardDeckDetailView,
    FlashcardCreateView,
    FlashcardUpdateView,
    FlashcardPreviewView,
    QuestionListView,
    QuestionDetailView,
    QuestionCreateView,
    QuestionEditView,
    QuestionCloneView,
    QuestionStudentPreviewView,
    QuestionReviewView,
    ReviewQueueView,
    QuestionValidateView,
    QuestionLifecycleActionView,
    QuestionHistoricalVersionView,
    QuestionVersionCompareView,
    QuestionHealthView,
    QuestionBulkActionView,
    QuestionUnitsHtmxView,
    QuestionLessonsHtmxView,
    ImportOverviewView,
    ImportUploadView,
    ImportPreviewView,
    ImportConfirmView,
    ImportLogDetailView,
    AssessmentsHubView,
    MinisterialExamListView,
    MinisterialExamDetailView,
    MinisterialExamValidateView,
    MinisterialExamRecalculateView,
    MinisterialExamReorderView,
    LessonMinisterialBatchesView,
    TrainingBatchListView,
    TrainingBatchDetailView,
    TrainingBatchSyncView,
    MockBlueprintListView,
    MockBlueprintVersionDetailView,
    MockBlueprintVersionPublishView,
    CustomTestReadinessView,
    SubscriptionsOverviewView,
    StudentSubscriptionListView,
    StudentSubscriptionDetailView,
    DirectActivationView,
    ActivationCodeBatchListView,
    ActivationCodeBatchCreateView,
    ActivationCodeListView,
    ActivationCodeUsageDetailView,
    SubscriptionAuditListView,
    SubscriptionPlanListView,
    SubscriptionPlanCreateView,
    SubscriptionPlanEditView,
    PlanEntitlementManageView,
    FreeAccessPolicyListView,
    FreeAccessPolicyEditView,
    ActivationCodeBatchRevokeView,
    SubscriptionRevokeView,
    NotificationsOverviewView,
    NotificationListView,
    NotificationCreateView,
    NotificationEditView,
    NotificationDetailView,
    NotificationScheduleView,
    NotificationCancelView,
    AudienceEstimateView,
    UserSearchAPIView,
    ActionDestinationPreviewView,
    StudentSearchView,
    StudentDetailView,
    StudentSessionRevokeView,
    StudentSessionRevokeAllView,
    ControlAuditListView,
    SystemHealthView,
)


app_name = "control"

urlpatterns = [
    # ─── Operations Dashboard ────────────────────────────────────────────────
    path("", DashboardView.as_view(), name="dashboard"),
    path("login/", ControlLoginView.as_view(), name="login"),
    path("logout/", ControlLogoutView.as_view(), name="logout"),

    # ─── Curriculum & Content Workspace (ADM-02) ─────────────────────────────
    path("content/", ContentHomeView.as_view(), name="content_home"),
    path("content/subjects/<str:subject_id>/", SubjectWorkspaceView.as_view(), name="subject_workspace"),
    path("content/units/<str:unit_id>/", UnitWorkspaceView.as_view(), name="unit_workspace"),
    path("content/lessons/<str:lesson_id>/", LessonWorkspaceView.as_view(), name="lesson_workspace"),

    # ─── Summaries ───────────────────────────────────────────────────────────
    path("content/summaries/add/", SummaryCreateView.as_view(), name="summary_create"),
    path("content/summaries/<uuid:pk>/edit/", SummaryUpdateView.as_view(), name="summary_update"),
    path("content/summaries/<uuid:pk>/preview/", SummaryPreviewView.as_view(), name="summary_preview"),
    path("content/summaries/<uuid:pk>/status/", SummaryStatusToggleView.as_view(), name="summary_status_toggle"),

    # ─── Lesson Explanations ─────────────────────────────────────────────────
    path("content/lessons/<str:lesson_id>/explanation/edit/", LessonExplanationEditView.as_view(), name="lesson_explanation_edit"),
    path("content/lessons/<str:lesson_id>/explanation/preview/", LessonExplanationPreviewView.as_view(), name="lesson_explanation_preview"),

    # ─── Flashcards Decks & Cards ────────────────────────────────────────────
    path("content/decks/add/", FlashcardDeckCreateView.as_view(), name="deck_create"),
    path("content/decks/<uuid:pk>/edit/", FlashcardDeckUpdateView.as_view(), name="deck_update"),
    path("content/decks/<uuid:pk>/", FlashcardDeckDetailView.as_view(), name="deck_detail"),
    path("content/decks/<uuid:deck_pk>/cards/add/", FlashcardCreateView.as_view(), name="card_create"),
    path("content/cards/<uuid:pk>/edit/", FlashcardUpdateView.as_view(), name="card_update"),
    path("content/cards/<uuid:pk>/preview/", FlashcardPreviewView.as_view(), name="card_preview"),

    # ─── Question Bank Workspace (ADM-03) ──────────────────────────────────
    path("questions/", QuestionListView.as_view(), name="question_list"),
    path("questions/create/", QuestionCreateView.as_view(), name="question_create"),
    path("questions/review-queue/", ReviewQueueView.as_view(), name="question_review_queue"),
    path("questions/health/", QuestionHealthView.as_view(), name="question_health"),
    path("questions/bulk/", QuestionBulkActionView.as_view(), name="question_bulk_action"),
    path("questions/htmx/units/", QuestionUnitsHtmxView.as_view(), name="question_htmx_units"),
    path("questions/htmx/lessons/", QuestionLessonsHtmxView.as_view(), name="question_htmx_lessons"),
    path("questions/<uuid:pk>/", QuestionDetailView.as_view(), name="question_detail"),
    path("questions/<uuid:pk>/edit/", QuestionEditView.as_view(), name="question_edit"),
    path("questions/<uuid:pk>/clone/", QuestionCloneView.as_view(), name="question_clone"),
    path("questions/<uuid:pk>/preview/", QuestionStudentPreviewView.as_view(), name="question_student_preview"),
    path("questions/<uuid:pk>/review/", QuestionReviewView.as_view(), name="question_review"),
    path("questions/<uuid:pk>/validate/", QuestionValidateView.as_view(), name="question_validate"),
    path("questions/<uuid:pk>/lifecycle/", QuestionLifecycleActionView.as_view(), name="question_lifecycle"),
    path("questions/<uuid:pk>/versions/<int:version_number>/", QuestionHistoricalVersionView.as_view(), name="question_version_detail"),
    path("questions/<uuid:pk>/compare/", QuestionVersionCompareView.as_view(), name="question_version_compare"),

    # ─── Import Center Workspace (ADM-04) ────────────────────────────────────
    path("imports/", ImportOverviewView.as_view(), name="import_overview"),
    path("imports/new/", ImportUploadView.as_view(), name="import_upload"),
    path("imports/preview/<str:token>/", ImportPreviewView.as_view(), name="import_preview"),
    path("imports/confirm/<str:token>/", ImportConfirmView.as_view(), name="import_confirm"),
    path("imports/logs/<uuid:id>/", ImportLogDetailView.as_view(), name="import_log_detail"),

    # ─── Assessments & Exam Operations Workspace (ADM-05) ───────────────────
    path("assessments/", AssessmentsHubView.as_view(), name="assessments_hub"),
    path("assessments/ministerial/", MinisterialExamListView.as_view(), name="ministerial_list"),
    path("assessments/ministerial/<uuid:pk>/", MinisterialExamDetailView.as_view(), name="ministerial_detail"),
    path("assessments/ministerial/<uuid:pk>/validate/", MinisterialExamValidateView.as_view(), name="ministerial_validate"),
    path("assessments/ministerial/<uuid:pk>/recalculate/", MinisterialExamRecalculateView.as_view(), name="ministerial_recalculate"),
    path("assessments/ministerial/<uuid:pk>/reorder/", MinisterialExamReorderView.as_view(), name="ministerial_reorder"),
    path("assessments/ministerial-batches/", LessonMinisterialBatchesView.as_view(), name="ministerial_batches"),
    path("assessments/ministerial/batches/", LessonMinisterialBatchesView.as_view()),
    path("assessments/training/", TrainingBatchListView.as_view(), name="training_list"),
    path("assessments/training/sync/", TrainingBatchSyncView.as_view(), name="training_sync"),
    path("assessments/training/<uuid:pk>/", TrainingBatchDetailView.as_view(), name="training_detail"),
    path("assessments/mock/", MockBlueprintListView.as_view(), name="mock_list"),
    path("assessments/mock/<uuid:blueprint_id>/version/<uuid:version_id>/", MockBlueprintVersionDetailView.as_view(), name="mock_version_detail"),
    path("assessments/mock/<uuid:blueprint_id>/version/<uuid:version_id>/publish/", MockBlueprintVersionPublishView.as_view(), name="mock_version_publish"),
    path("assessments/custom-tests/readiness/", CustomTestReadinessView.as_view(), name="custom_test_readiness"),

    # ─── Subscriptions & Access Operations Workspace (ADM-06) ───────────────
    path("subscriptions/", SubscriptionsOverviewView.as_view(), name="subscriptions_overview"),
    path("subscriptions/students/", StudentSubscriptionListView.as_view(), name="student_subscription_list"),
    path("subscriptions/students/<uuid:user_id>/", StudentSubscriptionDetailView.as_view(), name="student_subscription_detail"),
    path("subscriptions/students/<uuid:subscription_id>/revoke/", SubscriptionRevokeView.as_view(), name="subscription_revoke"),
    path("subscriptions/direct-activate/", DirectActivationView.as_view(), name="direct_activate"),
    path("subscriptions/codes/", ActivationCodeBatchListView.as_view(), name="activation_code_batch_list"),
    path("subscriptions/codes/generate/", ActivationCodeBatchCreateView.as_view(), name="activation_code_batch_generate"),
    path("subscriptions/codes/create/", ActivationCodeBatchCreateView.as_view(), name="activation_code_batch_create"),
    path("subscriptions/codes/batches/<uuid:batch_id>/revoke/", ActivationCodeBatchRevokeView.as_view(), name="activation_code_batch_revoke"),
    path("subscriptions/codes/lookup/", ActivationCodeListView.as_view(), name="activation_code_lookup"),
    path("subscriptions/codes/<uuid:pk>/", ActivationCodeUsageDetailView.as_view(), name="activation_code_detail"),
    path("subscriptions/codes/usage/<uuid:pk>/", ActivationCodeUsageDetailView.as_view(), name="activation_code_usage_detail"),
    path("subscriptions/audit/", SubscriptionAuditListView.as_view(), name="subscription_audit_list"),
    path("subscriptions/plans/", SubscriptionPlanListView.as_view(), name="subscription_plan_list"),
    path("subscriptions/plans/create/", SubscriptionPlanCreateView.as_view(), name="subscription_plan_create"),
    path("subscriptions/plans/<uuid:pk>/edit/", SubscriptionPlanEditView.as_view(), name="subscription_plan_edit"),
    path("subscriptions/plans/<uuid:plan_id>/entitlements/", PlanEntitlementManageView.as_view(), name="plan_entitlement_manage"),
    path("subscriptions/plans/<uuid:plan_id>/entitlements/manage/", PlanEntitlementManageView.as_view(), name="plan_entitlements_manage"),
    path("subscriptions/free-policy/", FreeAccessPolicyListView.as_view(), name="free_policy_list"),
    path("subscriptions/free-policy/create/", FreeAccessPolicyEditView.as_view(), name="free_policy_create"),
    path("subscriptions/free-policy/<uuid:pk>/edit/", FreeAccessPolicyEditView.as_view(), name="free_policy_edit"),

    # ─── Notifications Management Workspace (ADM-07) ─────────────────────────
    path("notifications/", NotificationsOverviewView.as_view(), name="notifications_overview"),
    path("notifications/list/", NotificationListView.as_view(), name="notification_list"),
    path("notifications/create/", NotificationCreateView.as_view(), name="notification_create"),
    path("notifications/<uuid:pk>/", NotificationDetailView.as_view(), name="notification_detail"),
    path("notifications/<uuid:pk>/edit/", NotificationEditView.as_view(), name="notification_edit"),
    path("notifications/<uuid:pk>/schedule/", NotificationScheduleView.as_view(), name="notification_schedule"),
    path("notifications/<uuid:pk>/cancel/", NotificationCancelView.as_view(), name="notification_cancel"),
    path("notifications/estimate-audience/", AudienceEstimateView.as_view(), name="notification_audience_estimate"),
    path("notifications/users/search/", UserSearchAPIView.as_view(), name="notification_user_search"),
    path("notifications/actions/preview/", ActionDestinationPreviewView.as_view(), name="notification_action_preview"),

    # ─── Student Support Workspace (ADM-08) ──────────────────────────────────
    path("students/", StudentSearchView.as_view(), name="student_list"),
    path("students/<uuid:user_id>/", StudentDetailView.as_view(), name="student_detail"),
    path("students/<uuid:user_id>/sessions/<uuid:session_id>/revoke/", StudentSessionRevokeView.as_view(), name="student_session_revoke"),
    path("students/<uuid:user_id>/sessions/revoke-all/", StudentSessionRevokeAllView.as_view(), name="student_session_revoke_all"),

    # ─── Central Audit Log & System Health (ADM-09) ──────────────────────────
    path("system/audit/", ControlAuditListView.as_view(), name="control_audit_list"),
    path("system/health/", SystemHealthView.as_view(), name="system_health"),
]

