# Generated by Django 5.1.15 on 2026-07-26 18:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('curriculum', '0001_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('entitlement_type', models.CharField(default='subject_access', max_length=50)),
                ('scope_type', models.CharField(default='subject', max_length=50)),
                ('limits', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.assessment')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.subject')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.unit')),
            ],
            options={
                'verbose_name': 'الاستحقاق',
                'verbose_name_plural': 'الاستحقاقات',
                'db_table': 'entitlements',
            },
        ),
        migrations.CreateModel(
            name='FreeAccessPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('free_units_count', models.PositiveIntegerField(default=1)),
                ('selection_strategy', models.CharField(choices=[('first_published', 'الوحدة الأولى المنشورة'), ('specific_units', 'وحدات محددة'), ('admin_selected', 'اختيار الإدارة')], default='first_published', max_length=30)),
                ('selected_units', models.JSONField(blank=True, default=list, help_text='["unit_id_1"]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.grade')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.section')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.subject')),
            ],
            options={
                'verbose_name': 'سياسة الوصول المجاني',
                'verbose_name_plural': 'سياسات الوصول المجاني',
                'db_table': 'entitlements_free_access_policies',
            },
        ),
        migrations.CreateModel(
            name='UserEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='subscription', max_length=50)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entitlements.entitlement')),
                ('study_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.studyenrollment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_entitlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'استحقاق المستخدم',
                'verbose_name_plural': 'استحقاقات المستخدمين',
                'db_table': 'entitlements_user_entitlements',
            },
        ),
        migrations.CreateModel(
            name='PlanEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entitlements.entitlement')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_entitlements', to='subscriptions.subscriptionplan')),
            ],
            options={
                'db_table': 'entitlements_plan_entitlements',
                'unique_together': {('plan', 'entitlement')},
            },
        ),
    ]
