# Generated by Django 5.1.15 on 2026-07-28 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessmentversion_allowed_attempt_modes_and_more'),
        ('curriculum', '0003_alter_unit_term'),
        ('entitlements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planentitlement',
            options={'verbose_name': 'استحقاق الخطة', 'verbose_name_plural': 'استحقاقات الخطط'},
        ),
        migrations.RemoveField(
            model_name='freeaccesspolicy',
            name='free_units_count',
        ),
        migrations.RemoveField(
            model_name='freeaccesspolicy',
            name='selected_units',
        ),
        migrations.RemoveField(
            model_name='freeaccesspolicy',
            name='selection_strategy',
        ),
        migrations.AddField(
            model_name='entitlement',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements', to='curriculum.grade'),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements', to='curriculum.section'),
        ),
        migrations.AddField(
            model_name='freeaccesspolicy',
            name='free_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='free_access_policies', to='curriculum.unit'),
        ),
        migrations.AddField(
            model_name='userentitlement',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_user_entitlements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userentitlement',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userentitlement',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userentitlement',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_user_entitlements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entitlement',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements', to='assessments.assessment'),
        ),
        migrations.AlterField(
            model_name='entitlement',
            name='entitlement_type',
            field=models.CharField(choices=[('full_access', 'وصول كامل'), ('subject_access', 'وصول لمادة'), ('unit_access', 'وصول لوحدة'), ('assessment_access', 'وصول لاختبار')], default='subject_access', max_length=50),
        ),
        migrations.AlterField(
            model_name='entitlement',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='entitlement',
            name='scope_type',
            field=models.CharField(choices=[('platform', 'منصة كاملة'), ('grade', 'صف دراسي كامل'), ('section', 'قسم دراسي كامل'), ('subject', 'مادة دراسية'), ('unit', 'وحدة دراسية'), ('assessment', 'اختبار مخصص')], db_index=True, default='subject', max_length=50),
        ),
        migrations.AlterField(
            model_name='entitlement',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements', to='curriculum.subject'),
        ),
        migrations.AlterField(
            model_name='entitlement',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements', to='curriculum.unit'),
        ),
        migrations.AlterField(
            model_name='freeaccesspolicy',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_policies', to='curriculum.grade'),
        ),
        migrations.AlterField(
            model_name='freeaccesspolicy',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='freeaccesspolicy',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_policies', to='curriculum.section'),
        ),
        migrations.AlterField(
            model_name='freeaccesspolicy',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='free_policies', to='curriculum.subject'),
        ),
        migrations.AlterField(
            model_name='planentitlement',
            name='entitlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_entitlements', to='entitlements.entitlement'),
        ),
        migrations.AlterField(
            model_name='userentitlement',
            name='entitlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_entitlements', to='entitlements.entitlement'),
        ),
        migrations.AlterField(
            model_name='userentitlement',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='userentitlement',
            name='source',
            field=models.CharField(default='administrative', max_length=50),
        ),
        migrations.AlterField(
            model_name='userentitlement',
            name='study_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_entitlements', to='curriculum.studyenrollment'),
        ),
        migrations.AddConstraint(
            model_name='freeaccesspolicy',
            constraint=models.UniqueConstraint(fields=('grade', 'section', 'subject'), name='unique_free_policy_per_subject'),
        ),
    ]
