# Generated by Django 5.1.15 on 2026-09-02 01:16

import django.db.models.deletion
from django.db import migrations, models


def seed_free_policies(apps, schema_editor):
    AcademicYear = apps.get_model("curriculum", "AcademicYear")
    Subject = apps.get_model("curriculum", "Subject")
    Unit = apps.get_model("curriculum", "Unit")
    Policy = apps.get_model("entitlements", "FreeAccessPolicy")
    year = AcademicYear.objects.filter(status="active").first()
    if year is None:
        return
    Policy.objects.filter(academic_year__isnull=True).update(academic_year=year)
    for subject in Subject.objects.filter(status="published"):
        unit = Unit.objects.filter(subject=subject, status="published").order_by("sort_order", "id").first()
        Policy.objects.get_or_create(
            academic_year=year, grade_id=subject.grade_id,
            section_id=subject.section_id, subject_id=subject.id,
            defaults={"free_unit_id": unit.id if unit else None},
        )


class Migration(migrations.Migration):

    # PostgreSQL cannot build the replacement unique index in the same atomic
    # transaction that updates rows protected by deferred FK triggers.
    atomic = False

    dependencies = [
        ('curriculum', '0005_academicyear_studyenrollment_academic_year'),
        ('entitlements', '0002_alter_planentitlement_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='freeaccesspolicy',
            name='unique_free_policy_per_subject',
        ),
        migrations.AddField(
            model_name='freeaccesspolicy',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='free_access_policies', to='curriculum.academicyear'),
        ),
        migrations.AddField(
            model_name='freeaccesspolicy',
            name='free_ministerial_count',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='freeaccesspolicy',
            name='free_mock_generations',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='freeaccesspolicy',
            name='free_subject_custom_generations',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='freeaccesspolicy',
            name='free_subject_training_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='freeaccesspolicy',
            name='subject_summaries_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='freeaccesspolicy',
            constraint=models.UniqueConstraint(fields=('academic_year', 'grade', 'section', 'subject'), name='unique_free_policy_per_subject_year'),
        ),
        migrations.RunPython(seed_free_policies, migrations.RunPython.noop),
    ]
