# Generated by Django 5.1.15 on 2026-07-26 18:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('link_type', models.CharField(choices=[('video', 'فيديو'), ('youtube', 'يوتيوب'), ('article', 'مقالة'), ('website', 'موقع'), ('pdf', 'ملف PDF'), ('file', 'ملف'), ('other', 'آخر')], db_index=True, default='video', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('thumbnail_path', models.ImageField(blank=True, null=True, upload_to='content_links/thumbnails/')),
                ('attached_file_path', models.FileField(blank=True, null=True, upload_to='content_links/files/')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('under_review', 'قيد المراجعة'), ('approved', 'معتمد'), ('published', 'منشور'), ('archived', 'مؤرشف')], db_index=True, default='published', max_length=20)),
                ('is_external', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_links', to='curriculum.lesson')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_links', to='curriculum.subject')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_links', to='curriculum.unit')),
            ],
            options={
                'verbose_name': 'رابط المحتوى',
                'verbose_name_plural': 'روابط المحتوى',
                'db_table': 'content_links',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlashcardDeck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('under_review', 'قيد المراجعة'), ('approved', 'معتمد'), ('published', 'منشور'), ('archived', 'مؤرشف')], db_index=True, default='published', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcard_decks', to='curriculum.lesson')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcard_decks', to='curriculum.subject')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcard_decks', to='curriculum.unit')),
            ],
            options={
                'verbose_name': 'حزمة البطاقات',
                'verbose_name_plural': 'حزم البطاقات التعليمية',
                'db_table': 'content_flashcard_decks',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('front_text', models.TextField(blank=True, null=True)),
                ('back_text', models.TextField(blank=True, null=True)),
                ('front_image_path', models.ImageField(blank=True, null=True, upload_to='flashcards/front/')),
                ('back_image_path', models.ImageField(blank=True, null=True, upload_to='flashcards/back/')),
                ('explanation', models.TextField(blank=True, null=True)),
                ('difficulty', models.CharField(default='medium', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='content.flashcarddeck')),
            ],
            options={
                'verbose_name': 'بطاقة تعليمية',
                'verbose_name_plural': 'البطاقات التعليمية',
                'db_table': 'content_flashcards',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary_type', models.CharField(choices=[('subject', 'ملخص مادة'), ('unit', 'ملخص وحدة'), ('lesson', 'ملخص درس'), ('final_review', 'مراجعة نهائية'), ('quick_review', 'مراجعة سريعة')], db_index=True, default='lesson', max_length=20)),
                ('body', models.TextField(blank=True, null=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='summaries/')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('file_checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('under_review', 'قيد المراجعة'), ('approved', 'معتمد'), ('published', 'منشور'), ('archived', 'مؤرشف')], db_index=True, default='published', max_length=20)),
                ('is_downloadable', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summaries', to='curriculum.lesson')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summaries', to='curriculum.subject')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summaries', to='curriculum.unit')),
            ],
            options={
                'verbose_name': 'الملخص',
                'verbose_name_plural': 'الملخصات',
                'db_table': 'content_summaries',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
