# Generated by Django 5.1.15 on 2026-07-27 19:42

import apps.content.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('curriculum', '0003_alter_unit_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonExplanation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField()),
                ('content_format', models.CharField(choices=[('plain_text', 'نص عادي'), ('markdown', 'Markdown')], default='markdown', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('under_review', 'قيد المراجعة'), ('approved', 'معتمد'), ('published', 'منشور'), ('archived', 'مؤرشف')], db_index=True, default='published', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'شرح الدرس',
                'verbose_name_plural': 'شروحات الدروس',
                'db_table': 'content_lesson_explanations',
            },
        ),
        migrations.AlterField(
            model_name='contentlink',
            name='attached_file_path',
            field=models.FileField(blank=True, null=True, upload_to=apps.content.models.generate_content_link_file_path),
        ),
        migrations.AlterField(
            model_name='contentlink',
            name='thumbnail_path',
            field=models.ImageField(blank=True, null=True, upload_to=apps.content.models.generate_content_link_thumbnail_path),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='back_image_path',
            field=models.ImageField(blank=True, null=True, upload_to=apps.content.models.generate_flashcard_back_image_path),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='front_image_path',
            field=models.ImageField(blank=True, null=True, upload_to=apps.content.models.generate_flashcard_front_image_path),
        ),
        migrations.AlterField(
            model_name='summary',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to=apps.content.models.generate_summary_file_path),
        ),
        migrations.AddConstraint(
            model_name='flashcard',
            constraint=models.UniqueConstraint(fields=('deck', 'sort_order'), name='unique_flashcard_sort_order_per_deck'),
        ),
        migrations.AddField(
            model_name='lessonexplanation',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='explanation', to='curriculum.lesson'),
        ),
    ]
