# Generated by Django 5.1.15 on 2026-09-08 03:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('session_revoke', 'سحب جلسة'), ('session_revoke_all', 'سحب جميع الجلسات'), ('subscription_activate', 'تفعيل اشتراك مباشر'), ('subscription_revoke', 'إلغاء/سحب اشتراك'), ('code_batch_generate', 'توليد دفعة رموز تفعيل'), ('code_batch_revoke', 'إلغاء دفعة رموز تفعيل'), ('notification_schedule', 'جدولة إشعار'), ('notification_publish', 'نشر إشعار فوري'), ('notification_cancel', 'إلغاء إشعار'), ('question_publish', 'نشر سؤال'), ('question_retire', 'أرشفة/استبعاد سؤال'), ('question_review', 'مراجعة/اعتماد سؤال'), ('ministerial_sync', 'مزامنة امتحان وزاري'), ('training_sync', 'مزامنة دفعات تدريبية'), ('blueprint_publish', 'نشر مخطط اختبار'), ('import_execute', 'تنفيذ عملية استيراد'), ('other', 'عملية تشغيلية أخرى')], db_index=True, help_text='رمز العملية المنفذة.', max_length=50)),
                ('target_type', models.CharField(db_index=True, help_text='نوع الكائن المستهدف (مثل: user_session, subscription, notification...).', max_length=60)),
                ('target_id', models.CharField(blank=True, db_index=True, default='', help_text='المعرّف الفريد للهدف المستهدف.', max_length=255)),
                ('target_repr', models.CharField(blank=True, default='', help_text='وصف أو عنوان الهدف لسهولة القراءة والبحث.', max_length=255)),
                ('reason', models.TextField(blank=True, default='', help_text='سبب تنفيذ العملية إن وجد.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='بيانات سياقية آمنة وخالية من الأسرار والرموز الحساسة.')),
                ('request_id', models.CharField(blank=True, db_index=True, help_text='معرّف الطلب أو التتبع (Correlation ID) إن توفر.', max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='عنوان IP داخلي للأمان والتدقيق الداخلي فقط.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='الموظف أو المدير الذي نفذ العملية.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل تدقيق العمليات',
                'verbose_name_plural': 'سجلات تدقيق العمليات',
                'db_table': 'control_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='control_aud_action_7ab41d_idx'), models.Index(fields=['target_type', 'target_id'], name='control_aud_target__a21cd2_idx'), models.Index(fields=['actor', 'created_at'], name='control_aud_actor_i_0108ac_idx')],
            },
        ),
    ]
