# Generated by Django 5.1.15 on 2026-07-26 18:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('curriculum', '0001_initial'),
        ('question_bank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_attempt_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('attempt_type', models.CharField(choices=[('normal', 'عادي'), ('retry_full', 'إعادة كاملة'), ('wrong_answers', 'إعادة الخاطئة'), ('unanswered', 'إعادة غير المجابة'), ('review_flagged', 'إعادة المؤشرة')], db_index=True, default='normal', max_length=30)),
                ('status', models.CharField(choices=[('created', 'تم الإنشاء'), ('in_progress', 'قيد التدريب'), ('paused', 'مؤقت'), ('submitted', 'مُسلّم'), ('evaluated', 'مُقيّم'), ('expired', 'منتهي'), ('cancelled', 'ملغى')], db_index=True, default='created', max_length=20)),
                ('display_mode', models.CharField(default='single', max_length=20)),
                ('questions_shuffled', models.BooleanField(default=False)),
                ('options_shuffled', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('current_question_id', models.UUIDField(blank=True, null=True)),
                ('answered_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('incorrect_count', models.PositiveIntegerField(default=0)),
                ('unanswered_count', models.PositiveIntegerField(default=0)),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('maximum_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.assessment')),
                ('assessment_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.assessmentversion')),
                ('blueprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.assessmentblueprint')),
                ('parent_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_attempts', to='attempts.assessmentattempt')),
                ('study_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_attempts', to='curriculum.studyenrollment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'محاولة اختبار',
                'verbose_name_plural': 'محاولات الاختبارات',
                'db_table': 'assessment_attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttemptAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_breakdown', models.JSONField(blank=True, default=dict)),
                ('lesson_breakdown', models.JSONField(blank=True, default=dict)),
                ('difficulty_breakdown', models.JSONField(blank=True, default=dict)),
                ('year_breakdown', models.JSONField(blank=True, default=dict)),
                ('source_breakdown', models.JSONField(blank=True, default=dict)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('version', models.PositiveIntegerField(default=1)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='attempts.assessmentattempt')),
            ],
            options={
                'db_table': 'attempt_analyses',
            },
        ),
        migrations.CreateModel(
            name='AttemptQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(default='ministerial', max_length=30)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('points', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('options_order_snapshot', models.JSONField(blank=True, default=list)),
                ('source_metadata_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_questions', to='attempts.assessmentattempt')),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='question_bank.questionversion')),
            ],
            options={
                'db_table': 'attempt_questions',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='AttemptStimulus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stimulus_type', models.CharField(default='reading_passage', max_length=30)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('image_path_snapshot', models.CharField(blank=True, max_length=500, null=True)),
                ('file_path_snapshot', models.CharField(blank=True, max_length=500, null=True)),
                ('layout', models.CharField(default='text_only', max_length=30)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_stimuli', to='attempts.assessmentattempt')),
                ('source_stimulus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='question_bank.questionstimulus')),
            ],
            options={
                'db_table': 'attempt_stimuli',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='AttemptQuestionStimulus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stimulus_links', to='attempts.attemptquestion')),
                ('attempt_stimulus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_links', to='attempts.attemptstimulus')),
            ],
            options={
                'db_table': 'attempt_question_stimuli',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_option_id', models.UUIDField(blank=True, null=True)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('awarded_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('client_updated_at', models.DateTimeField(blank=True, null=True)),
                ('server_updated_at', models.DateTimeField(auto_now=True)),
                ('response_time_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='attempts.assessmentattempt')),
                ('attempt_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='attempts.attemptquestion')),
            ],
            options={
                'verbose_name': 'إجابة المحاولة',
                'verbose_name_plural': 'إجابات المحاولات',
                'db_table': 'attempt_answers',
                'unique_together': {('attempt', 'attempt_question')},
            },
        ),
    ]
