# Generated by Django 5.1.15 on 2026-07-27 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessmentversion_allowed_attempt_modes_and_more'),
        ('attempts', '0001_initial'),
        ('question_bank', '0003_questionasset_unique_question_asset_order_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attemptanswer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='mode',
            field=models.CharField(choices=[('practice', 'تدريب (فوري)'), ('exam', 'اختبار (نهائي)')], db_index=True, default='exam', max_length=20),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='pending_review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='answer_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='assessment_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.assessmentitem'),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='question_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='assessmentattempt',
            name='status',
            field=models.CharField(choices=[('created', 'تم الإنشاء'), ('in_progress', 'قيد التدريب'), ('paused', 'مؤقت'), ('submitted', 'مُسلّم'), ('evaluated', 'مُقيّم'), ('pending_review', 'قيد المراجعة اليدوية'), ('expired', 'منتهي'), ('cancelled', 'ملغى')], db_index=True, default='created', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='attemptanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'attempt_question'), name='unique_answer_per_attempt_question'),
        ),
        migrations.AddConstraint(
            model_name='attemptquestion',
            constraint=models.UniqueConstraint(fields=('attempt', 'sort_order'), name='unique_attempt_question_order'),
        ),
    ]
