# Generated by Django 5.1.15 on 2026-08-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0002_alter_attemptanswer_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentattempt',
            name='contract_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='feedback_policy',
            field=models.CharField(default='deferred', max_length=20),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='official_maximum_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='timing_mode',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='client_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='is_evaluated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='is_visited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='selected_option_key',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='server_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='is_reference',
            field=models.BooleanField(default=False),
        ),
    ]
