# Generated by Django 5.1.15 on 2026-08-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0003_assessmentattempt_contract_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentattempt',
            name='auto_submit_on_expiry',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='frozen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='submission_reason',
            field=models.CharField(default='manual', max_length=30),
        ),
    ]
