# Generated by Django 5.1.15 on 2026-07-26 18:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinisterialExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_code', models.CharField(db_index=True, max_length=100)),
                ('exam_year', models.PositiveIntegerField(db_index=True)),
                ('exam_role', models.CharField(blank=True, choices=[('first', 'الدور الأول'), ('second', 'الدور الثاني'), ('supplementary', 'تكميلي'), ('other', 'آخر')], db_index=True, max_length=20, null=True)),
                ('model_number', models.CharField(default='1', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('total_points', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('source_file_path', models.FileField(blank=True, null=True, upload_to='ministerial_exams/')),
                ('source_checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('under_review', 'قيد المراجعة'), ('approved', 'معتمد'), ('published', 'منشور'), ('archived', 'مؤرشف')], db_index=True, default='published', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ministerial_exams', to='curriculum.subject')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministerial_exams', to='curriculum.term')),
            ],
            options={
                'verbose_name': 'النموذج الوزاري',
                'verbose_name_plural': 'النماذج الوزارية',
                'db_table': 'ministerial_exams',
                'ordering': ['-exam_year', 'model_number'],
            },
        ),
        migrations.CreateModel(
            name='MinisterialExamSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ministerial_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ministerial_exams.ministerialexam')),
                ('stimulus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='question_bank.questionstimulus')),
            ],
            options={
                'db_table': 'ministerial_exam_sections',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='MinisterialExamItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_number', models.PositiveIntegerField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('points', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('official_options_order', models.JSONField(blank=True, default=list, help_text='["A", "B", "C", "D"]')),
                ('source_page', models.PositiveIntegerField(blank=True, null=True)),
                ('source_image_path', models.ImageField(blank=True, null=True, upload_to='ministerial_exams/items/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ministerial_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ministerial_exams.ministerialexam')),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ministerial_items', to='question_bank.questionversion')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='ministerial_exams.ministerialexamsection')),
            ],
            options={
                'verbose_name': 'عنصر نموذج وزاري',
                'verbose_name_plural': 'عناصر النماذج الوزارية',
                'db_table': 'ministerial_exam_items',
                'ordering': ['sort_order', 'question_number'],
            },
        ),
    ]
