# Generated by Django 5.1.15 on 2026-07-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_alter_unit_term'),
        ('ministerial_exams', '0001_initial'),
        ('question_bank', '0003_questionasset_unique_question_asset_order_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ministerialexam',
            constraint=models.UniqueConstraint(fields=('subject', 'exam_year', 'exam_role', 'model_number'), name='unique_ministerial_exam_per_subject_year_role_model'),
        ),
        migrations.AddConstraint(
            model_name='ministerialexamitem',
            constraint=models.UniqueConstraint(fields=('ministerial_exam', 'question_number'), name='unique_exam_question_number'),
        ),
        migrations.AddConstraint(
            model_name='ministerialexamitem',
            constraint=models.UniqueConstraint(fields=('ministerial_exam', 'sort_order'), name='unique_exam_item_order'),
        ),
        migrations.AddConstraint(
            model_name='ministerialexamsection',
            constraint=models.UniqueConstraint(fields=('ministerial_exam', 'sort_order'), name='unique_exam_section_order'),
        ),
    ]
