# Generated by Django 5.1.15 on 2026-07-27 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessmentversion_allowed_attempt_modes_and_more'),
        ('ministerial_exams', '0002_ministerialexam_unique_ministerial_exam_per_subject_year_role_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministerialexam',
            name='assessment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministerial_exam', to='assessments.assessment'),
        ),
    ]
