# Generated by Django 5.1.15 on 2026-09-02 01:16

from django.db import migrations, models


def assign_ministerial_ranks(apps, schema_editor):
    Exam = apps.get_model("ministerial_exams", "MinisterialExam")
    subject_ids = Exam.objects.values_list("subject_id", flat=True).distinct()
    for subject_id in subject_ids:
        rows = Exam.objects.filter(subject_id=subject_id).order_by("created_at", "id")
        for rank, exam in enumerate(rows, 1):
            exam.free_access_rank = rank
            exam.save(update_fields=["free_access_rank"])


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('assessments', '0007_trainingbatch_free_access_rank_and_more'),
        ('curriculum', '0005_academicyear_studyenrollment_academic_year'),
        ('ministerial_exams', '0004_lesson_ministerial_batches'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministerialexam',
            name='free_access_rank',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(assign_ministerial_ranks, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='ministerialexam',
            constraint=models.UniqueConstraint(condition=models.Q(('free_access_rank__isnull', False)), fields=('subject', 'free_access_rank'), name='unique_ministerial_free_rank_per_subject'),
        ),
    ]
