"""
OTP Service.

Handles generating, HMAC-hashing, sending, and verifying OTP codes.
Produces secure verification grants for downstream registration/login flows.
"""

import hashlib
import hmac
import logging
import random
import secrets
import string
from datetime import timedelta

from django.conf import settings
from django.db import transaction
from django.db.models import F
from django.utils import module_loading, timezone

from apps.accounts.exceptions import (
    InvalidOTPError,
    InvalidPhoneError,
    OTPAttemptsExceededError,
    OTPCooldownError,
    OTPExpiredError,
    VerificationGrantError,
)
from apps.accounts.models import PhoneVerification, normalize_phone
from apps.accounts.providers.base import OTPProvider

logger = logging.getLogger("accounts.services")


def _hmac_hash(data: str) -> str:
    """HMAC-SHA256 hash using OTP_HASH_SECRET."""
    secret = getattr(settings, "OTP_HASH_SECRET", "")
    if not secret:
        raise RuntimeError("OTP_HASH_SECRET is not configured.")
    return hmac.new(
        secret.encode("utf-8"),
        data.encode("utf-8"),
        hashlib.sha256,
    ).hexdigest()


def hash_otp_code(code: str, phone: str, purpose: str, request_id: str) -> str:
    """
    Hash OTP code with HMAC-SHA256, binding to phone + purpose + request_id.

    This prevents rainbow table attacks on the 6-digit OTP space.
    """
    data = f"{phone}:{purpose}:{request_id}:{code}"
    return _hmac_hash(data)


def get_otp_provider() -> OTPProvider:
    """Instantiate configured OTPProvider class."""
    provider_path = settings.OTP_SETTINGS.get(
        "SMS_PROVIDER",
        "apps.accounts.providers.fake_provider.FakeOTPProvider",
    )
    provider_cls = module_loading.import_string(provider_path)
    return provider_cls()


def generate_otp_code(length: int = 6) -> str:
    """Generate numeric OTP code using cryptographically secure random."""
    return "".join(secrets.choice(string.digits) for _ in range(length))


@transaction.atomic
def request_phone_otp(
    phone: str,
    purpose: str,
    request_ip: str | None = None,
    installation_id: str | None = None,
) -> PhoneVerification:
    """
    Generate and send an OTP code to a phone number.

    - Invalidates any previous active OTP for the same phone+purpose.
    - Enforces cooldown between requests.
    - Returns the PhoneVerification record (without plaintext code).
    """
    normalized_phone = normalize_phone(phone)

    if not normalized_phone or not normalized_phone.startswith("+967"):
        raise InvalidPhoneError("رقم الهاتف يجب أن يكون بصيغة يمنية طويلة (+9677XXXXXXXX).")

    # Check cooldown on recent requests
    cooldown_seconds = settings.OTP_SETTINGS.get("RESEND_COOLDOWN_SECONDS", 60)
    cutoff = timezone.now() - timedelta(seconds=cooldown_seconds)

    recent = PhoneVerification.objects.filter(
        phone=normalized_phone,
        purpose=purpose,
        last_sent_at__gte=cutoff,
        consumed_at__isnull=True,
    ).first()

    if recent:
        remaining = cooldown_seconds - int((timezone.now() - recent.last_sent_at).total_seconds())
        raise OTPCooldownError(remaining_seconds=max(remaining, 1))

    # Invalidate all previous active OTPs for same phone + purpose
    PhoneVerification.objects.filter(
        phone=normalized_phone,
        purpose=purpose,
        consumed_at__isnull=True,
        expires_at__gt=timezone.now(),
    ).update(consumed_at=timezone.now())

    code = generate_otp_code(length=settings.OTP_SETTINGS.get("CODE_LENGTH", 6))

    expiry_seconds = settings.OTP_SETTINGS.get("CODE_EXPIRY_SECONDS", 300)
    expires_at = timezone.now() + timedelta(seconds=expiry_seconds)

    # Create verification record — request_id is auto-generated by UUID default
    import uuid
    request_id = uuid.uuid4()

    code_hash = hash_otp_code(code, normalized_phone, purpose, str(request_id))

    verification = PhoneVerification.objects.create(
        phone=normalized_phone,
        purpose=purpose,
        code_hash=code_hash,
        request_id=request_id,
        expires_at=expires_at,
        request_ip=request_ip,
        installation_id=installation_id,
    )

    # Send SMS via provider
    provider = get_otp_provider()
    result = provider.send_otp(phone=normalized_phone, code=code, purpose=purpose)

    if not result.success:
        logger.error("Failed to send OTP SMS for purpose=%s: %s", purpose, result.error_message)

    return verification


def verify_phone_otp(
    request_id: str,
    phone: str,
    code: str,
    purpose: str,
) -> tuple[PhoneVerification, str]:
    """
    Verify an OTP code and produce a one-time verification grant.

    Returns:
        (verification_record, verification_grant_token)

    The grant token must be passed to RegisterComplete/Login as proof.
    The OTP is NOT consumed here — consumption happens when the grant is used.
    Uses select_for_update inside transaction.atomic for safe concurrency.
    """
    normalized_phone = normalize_phone(phone)
    grant_token = None
    is_invalid_code = False

    with transaction.atomic():
        # Lock the record to prevent concurrent verification
        verification = (
            PhoneVerification.objects.select_for_update()
            .filter(
                request_id=request_id,
                phone=normalized_phone,
                purpose=purpose,
            )
            .first()
        )

        if not verification:
            raise InvalidOTPError("طلب التحقق غير موجود.")

        if verification.consumed_at is not None:
            raise InvalidOTPError("تم استخدام رمز التحقق هذا من قبل.")

        if verification.verified_at is not None:
            raise InvalidOTPError("تم التحقق من هذا الطلب بالفعل.")

        max_attempts = settings.OTP_SETTINGS.get("MAX_ATTEMPTS", 5)
        if verification.attempts_count >= max_attempts:
            raise OTPAttemptsExceededError()

        if verification.expires_at <= timezone.now():
            raise OTPExpiredError()

        # Check HMAC code hash
        expected_hash = hash_otp_code(code, normalized_phone, purpose, str(verification.request_id))
        if not hmac.compare_digest(verification.code_hash, expected_hash):
            PhoneVerification.objects.filter(id=verification.id).update(
                attempts_count=F("attempts_count") + 1
            )
            is_invalid_code = True
        else:
            # Success — generate verification grant
            grant_token = secrets.token_urlsafe(48)
            grant_hash = _hmac_hash(grant_token)

            verification.verified_at = timezone.now()
            verification.verification_grant_hash = grant_hash
            verification.save(update_fields=["verified_at", "verification_grant_hash"])

    if is_invalid_code:
        raise InvalidOTPError("رمز التحقق غير صحيح.")

    return verification, grant_token


@transaction.atomic
def consume_verification_grant(
    request_id: str | None = None,
    verification_grant: str = "",
    phone: str = "",
    purpose: str = "",
) -> PhoneVerification:
    """
    Validate and consume a one-time verification grant.

    This is called by RegisterComplete/Login to prove that OTP was verified.
    After consumption, the grant cannot be reused.

    Returns:
        The consumed PhoneVerification record.
    """
    normalized_phone = normalize_phone(phone)
    expected_hash = _hmac_hash(verification_grant)

    qs = PhoneVerification.objects.select_for_update().filter(
        phone=normalized_phone,
        purpose=purpose,
    )
    if request_id:
        qs = qs.filter(request_id=request_id)
    else:
        qs = qs.filter(verification_grant_hash=expected_hash)

    verification = qs.first()

    if not verification:
        raise VerificationGrantError("طلب التحقق غير موجود.")

    if verification.consumed_at is not None:
        raise VerificationGrantError("تم استخدام إثبات التحقق من قبل.")

    if verification.verified_at is None:
        raise VerificationGrantError("لم يتم التحقق من هذا الطلب بعد.")

    if verification.expires_at <= timezone.now():
        raise VerificationGrantError("انتهت صلاحية إثبات التحقق.")

    if not verification.verification_grant_hash:
        raise VerificationGrantError("لا يوجد إثبات تحقق لهذا الطلب.")

    # Verify grant hash
    if not hmac.compare_digest(verification.verification_grant_hash, expected_hash):
        raise VerificationGrantError("إثبات التحقق غير صحيح.")

    # Consume
    verification.consumed_at = timezone.now()
    verification.save(update_fields=["consumed_at"])

    return verification
