# Generated by Django 5.1.15 on 2026-07-26 18:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.CharField(help_text='مثال: 3s أو grade_12', max_length=50, primary_key=True, serialize=False)),
                ('name_ar', models.CharField(max_length=150)),
                ('name_en', models.CharField(blank=True, default='', max_length=150)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'الصف الدراسي',
                'verbose_name_plural': 'الصفوف الدراسية',
                'db_table': 'curriculum_grades',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.CharField(help_text='مثال: 3s_sci_chem_fy_u1_l1', max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('estimated_minutes', models.PositiveIntegerField(default=15)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('under_review', 'قيد المراجعة'), ('approved', 'معتمد'), ('published', 'منشور'), ('archived', 'مؤرشف')], db_index=True, default='published', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'الدرس الدراسي',
                'verbose_name_plural': 'الدروس الدراسية',
                'db_table': 'curriculum_lessons',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.CharField(help_text='مثال: 3s_sci أو scientific', max_length=50, primary_key=True, serialize=False)),
                ('name_ar', models.CharField(max_length=150)),
                ('name_en', models.CharField(blank=True, default='', max_length=150)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='curriculum.grade')),
            ],
            options={
                'verbose_name': 'القسم / المسار',
                'verbose_name_plural': 'الأقسام والمسارات',
                'db_table': 'curriculum_sections',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.CharField(help_text='مثال: 3s_sci_chem', max_length=100, primary_key=True, serialize=False)),
                ('name_ar', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('icon_path', models.FileField(blank=True, null=True, upload_to='subjects/icons/')),
                ('cover_image_path', models.ImageField(blank=True, null=True, upload_to='subjects/covers/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('under_review', 'قيد المراجعة'), ('approved', 'معتمد'), ('published', 'منشور'), ('archived', 'مؤرشف')], db_index=True, default='published', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='curriculum.grade')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='curriculum.section')),
            ],
            options={
                'verbose_name': 'المادة الدراسية',
                'verbose_name_plural': 'المواد الدراسية',
                'db_table': 'curriculum_subjects',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.CharField(help_text='مثال: fy أو term_01', max_length=50, primary_key=True, serialize=False)),
                ('name_ar', models.CharField(max_length=150)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='curriculum.grade')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='curriculum.section')),
            ],
            options={
                'verbose_name': 'الفصل الدراسي',
                'verbose_name_plural': 'الفصول الدراسية',
                'db_table': 'curriculum_terms',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('under_review', 'قيد المراجعة'), ('approved', 'معتمد'), ('published', 'منشور'), ('archived', 'مؤرشف')], db_index=True, default='published', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='curriculum.lesson')),
            ],
            options={
                'verbose_name': 'موضوع تفصيلي',
                'verbose_name_plural': 'المواضيع التفصيلية',
                'db_table': 'curriculum_topics',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.CharField(help_text='مثال: 3s_sci_chem_fy_u1', max_length=150, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('under_review', 'قيد المراجعة'), ('approved', 'معتمد'), ('published', 'منشور'), ('archived', 'مؤرشف')], db_index=True, default='published', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='curriculum.subject')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='curriculum.term')),
            ],
            options={
                'verbose_name': 'الوحدة الدراسية',
                'verbose_name_plural': 'الوحدات الدراسية',
                'db_table': 'curriculum_units',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='curriculum.unit'),
        ),
        migrations.CreateModel(
            name='StudyEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'نشط'), ('changed', 'مُغيَّر'), ('cancelled', 'ملغى')], db_index=True, default='active', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='curriculum.grade')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='curriculum.section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'الملف الدراسي',
                'verbose_name_plural': 'الملفات الدراسية',
                'db_table': 'curriculum_study_enrollments',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='unique_active_enrollment_per_user')],
            },
        ),
    ]
