# Generated by Django 5.1.15 on 2026-07-27 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='term',
            field=models.ForeignKey(default='fy', help_text='الفصل الدراسي التابع له هذه الوحدة.', on_delete=django.db.models.deletion.PROTECT, related_name='units', to='curriculum.term'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('unit', 'sort_order'), name='unique_lesson_sort_order_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('lesson', 'sort_order'), name='unique_topic_sort_order_per_lesson'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('subject', 'sort_order'), name='unique_unit_sort_order_per_subject'),
        ),
    ]
