# Generated by Django 5.1.15 on 2026-07-27 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_alter_unit_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='term',
            field=models.ForeignKey(help_text='الفصل الدراسي التابع له هذه الوحدة.', on_delete=django.db.models.deletion.PROTECT, related_name='units', to='curriculum.term'),
        ),
    ]
