# Generated by Django 5.1.15 on 2026-09-02 01:16

import django.db.models.deletion
from datetime import datetime, timezone
from django.db import migrations, models


def seed_current_academic_year(apps, schema_editor):
    AcademicYear = apps.get_model("curriculum", "AcademicYear")
    StudyEnrollment = apps.get_model("curriculum", "StudyEnrollment")
    year, _ = AcademicYear.objects.get_or_create(
        code="2026-2027",
        defaults={
            "name_ar": "العام الدراسي 2026-2027",
            "starts_at": datetime(2026, 9, 1, tzinfo=timezone.utc),
            "ends_at": datetime(2027, 7, 31, 20, 59, 59, tzinfo=timezone.utc),
            "status": "active",
        },
    )
    StudyEnrollment.objects.filter(academic_year__isnull=True).update(academic_year=year)


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_normalize_scoped_term_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name_ar', models.CharField(max_length=100)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('upcoming', 'قادم'), ('active', 'نشط'), ('closed', 'منتهي')], db_index=True, default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'العام الدراسي',
                'verbose_name_plural': 'الأعوام الدراسية',
                'db_table': 'curriculum_academic_years',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.AddField(
            model_name='studyenrollment',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='السياق السنوي الحالي. الحقل اختياري فقط للسجلات القديمة.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='curriculum.academicyear'),
        ),
        migrations.RunPython(seed_current_academic_year, migrations.RunPython.noop),
    ]
