# Generated by Django 5.1.15 on 2026-09-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_academicyear_studyenrollment_academic_year'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('status',), name='unique_active_academic_year'),
        ),
    ]
