# Generated by Django 5.1.15 on 2026-09-03 22:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_enforce_single_active_academic_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('offer', 'عرض'), ('package', 'باقة'), ('new_feature', 'ميزة جديدة'), ('update', 'تحديث'), ('announcement', 'إعلان')], db_index=True, default='announcement', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', max_length=300)),
                ('image_path', models.FileField(blank=True, null=True, upload_to='curriculum/banners/')),
                ('badge_text', models.CharField(blank=True, default='', max_length=50)),
                ('cta_label', models.CharField(blank=True, default='', max_length=100)),
                ('cta_type', models.CharField(choices=[('none', 'بدون إجراء'), ('subscription_catalog', 'دليل الاشتراكات'), ('subject', 'المادة'), ('unit', 'الوحدة'), ('lesson', 'الدرس'), ('downloads', 'التحميلات'), ('progress', 'التقدم'), ('settings', 'الإعدادات')], default='none', max_length=30)),
                ('target_id', models.CharField(blank=True, default='', help_text='معرف الهدف للربط الآمن (مثل معرف المادة أو الوحدة)', max_length=100)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_banners', to='curriculum.academicyear')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_banners', to='curriculum.grade')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_banners', to='curriculum.section')),
            ],
            options={
                'verbose_name': 'بانر الشاشة الرئيسية',
                'verbose_name_plural': 'بانرات الشاشة الرئيسية',
                'db_table': 'curriculum_dashboard_banners',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
