# Generated by Django 5.1.15 on 2026-07-26 18:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('ministerial_exams', '0001_initial'),
        ('question_bank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('assessment_type', models.CharField(choices=[('ministerial_exam', 'نموذج وزاري كامل'), ('lesson_test', 'اختبار درس'), ('unit_test', 'اختبار وحدة'), ('subject_test', 'اختبار مادة (محدود)'), ('self_practice', 'اختبر نفسك'), ('custom_test', 'اختبار مخصص'), ('training_test', 'اختبار تدريبي'), ('wrong_answers_test', 'إعادة الأسئلة الخاطئة'), ('unanswered_test', 'إعادة الأسئلة غير المجابة'), ('monthly_test', 'اختبار شهري'), ('group_test', 'اختبار مجموعات'), ('ai_generated_test', 'اختبار مصنع بالذكاء الاصطناعي')], db_index=True, default='lesson_test', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('under_review', 'قيد المراجعة'), ('approved', 'معتمد'), ('published', 'منشور'), ('archived', 'مؤرشف')], db_index=True, default='published', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='curriculum.lesson')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='curriculum.subject')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='curriculum.unit')),
            ],
            options={
                'verbose_name': 'الاختبار',
                'verbose_name_plural': 'الاختبارات',
                'db_table': 'assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentBlueprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_types', models.JSONField(blank=True, default=list)),
                ('years', models.JSONField(blank=True, default=list)),
                ('difficulties', models.JSONField(blank=True, default=list)),
                ('question_types', models.JSONField(blank=True, default=list)),
                ('question_count', models.PositiveIntegerField(default=10)),
                ('unit_distribution', models.JSONField(blank=True, null=True)),
                ('ministerial_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('training_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exclude_previously_answered', models.BooleanField(default=False)),
                ('max_questions_limit', models.PositiveIntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprints', to='assessments.assessment')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.lesson')),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='question_bank.questionpool')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.subject')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.unit')),
            ],
            options={
                'db_table': 'assessment_blueprints',
            },
        ),
        migrations.CreateModel(
            name='AssessmentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('total_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('question_count', models.PositiveIntegerField(default=0)),
                ('passing_percentage', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('allow_resume', models.BooleanField(default=True)),
                ('allow_answer_change', models.BooleanField(default=True)),
                ('allow_previous_question', models.BooleanField(default=True)),
                ('allowed_display_modes', models.JSONField(blank=True, default=list, help_text='["single", "full"]')),
                ('default_display_mode', models.CharField(default='single', max_length=20)),
                ('question_shuffle_policy', models.CharField(choices=[('never', 'أبداً'), ('always', 'دائماً'), ('user_choice', 'خيار المستخدم')], default='always', max_length=20)),
                ('option_shuffle_policy', models.CharField(choices=[('never', 'أبداً'), ('always', 'دائماً'), ('user_choice', 'خيار المستخدم')], default='always', max_length=20)),
                ('explanation_policy', models.CharField(default='after_submit', max_length=30)),
                ('is_current', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='assessments.assessment')),
            ],
            options={
                'verbose_name': 'نسخة الاختبار',
                'verbose_name_plural': 'نسخ الاختبارات',
                'db_table': 'assessment_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('points', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('official_options_order', models.JSONField(blank=True, default=list)),
                ('required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ministerial_exam_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministerial_exams.ministerialexamitem')),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='question_bank.questionversion')),
                ('assessment_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assessments.assessmentversion')),
            ],
            options={
                'db_table': 'assessment_items',
                'ordering': ['sort_order'],
            },
        ),
    ]
