# Generated by Django 5.1.15 on 2026-07-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('ministerial_exams', '0002_ministerialexam_unique_ministerial_exam_per_subject_year_role_model_and_more'),
        ('question_bank', '0003_questionasset_unique_question_asset_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentversion',
            name='allowed_attempt_modes',
            field=models.JSONField(blank=True, default=list, help_text='["practice", "exam"]'),
        ),
        migrations.AddConstraint(
            model_name='assessmentitem',
            constraint=models.UniqueConstraint(fields=('assessment_version', 'sort_order'), name='unique_assessment_item_order'),
        ),
        migrations.AddConstraint(
            model_name='assessmentitem',
            constraint=models.UniqueConstraint(fields=('assessment_version', 'question_version'), name='unique_question_per_assessment_version'),
        ),
        migrations.AddConstraint(
            model_name='assessmentversion',
            constraint=models.UniqueConstraint(fields=('assessment', 'version_number'), name='unique_assessment_version_number'),
        ),
        migrations.AddConstraint(
            model_name='assessmentversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('assessment',), name='unique_current_assessment_version'),
        ),
    ]
