# Generated by Django 5.1.15 on 2026-08-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessmentversion_allowed_attempt_modes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentversion',
            name='feedback_policy',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('deferred', 'Deferred')], default='deferred', max_length=20),
        ),
        migrations.AddField(
            model_name='assessmentversion',
            name='seconds_per_question',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentversion',
            name='timing_mode',
            field=models.CharField(choices=[('none', 'No timer'), ('fixed', 'Fixed duration'), ('calculated', 'Calculated per question')], default='none', max_length=20),
        ),
    ]
