# Generated by Django 5.1.15 on 2026-08-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessmentversion_feedback_policy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('ministerial_exam', 'نموذج وزاري كامل'), ('lesson_test', 'اختبار درس'), ('unit_test', 'اختبار وحدة'), ('subject_test', 'اختبار مادة (محدود)'), ('self_practice', 'اختبر نفسك'), ('custom_test', 'اختبار مخصص'), ('training_test', 'اختبار تدريبي'), ('wrong_answers_test', 'إعادة الأسئلة الخاطئة'), ('unanswered_test', 'إعادة الأسئلة غير المجابة'), ('monthly_test', 'اختبار شهري'), ('group_test', 'اختبار مجموعات'), ('ai_generated_test', 'اختبار مصنع بالذكاء الاصطناعي'), ('lesson_ministerial', 'Lesson ministerial practice')], db_index=True, default='lesson_test', max_length=30),
        ),
        migrations.AlterField(
            model_name='assessmentversion',
            name='feedback_policy',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('deferred', 'Deferred')], default='immediate', max_length=20),
        ),
    ]
