# Generated by Django 5.1.15 on 2026-08-23 21:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_alter_assessment_assessment_type_and_more'),
        ('curriculum', '0004_normalize_scoped_term_ids'),
        ('question_bank', '0005_question_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_type', models.CharField(choices=[('lesson', 'درس'), ('unit', 'وحدة'), ('subject', 'مادة')], max_length=20)),
                ('scope_key', models.CharField(db_index=True, max_length=255)),
                ('batch_index', models.PositiveIntegerField()),
                ('target_size', models.PositiveIntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_batches', to='curriculum.lesson')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_batches', to='curriculum.subject')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_batches', to='curriculum.unit')),
            ],
            options={
                'db_table': 'assessment_training_batches',
                'ordering': ['batch_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingBatchItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.PositiveIntegerField()),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assessments.trainingbatch')),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_batch_items', to='question_bank.questionversion')),
            ],
            options={
                'db_table': 'assessment_training_batch_items',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='trainingbatch',
            constraint=models.UniqueConstraint(fields=('scope_key', 'batch_index'), name='unique_training_batch_scope_index'),
        ),
        migrations.AddConstraint(
            model_name='trainingbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lesson__isnull', False), ('scope_type', 'lesson'), ('unit__isnull', False)), models.Q(('lesson__isnull', True), ('scope_type', 'unit'), ('unit__isnull', False)), models.Q(('lesson__isnull', True), ('scope_type', 'subject'), ('unit__isnull', True)), _connector='OR'), name='valid_training_batch_scope'),
        ),
        migrations.AddConstraint(
            model_name='trainingbatchitem',
            constraint=models.UniqueConstraint(fields=('batch', 'sort_order'), name='unique_training_batch_item_order'),
        ),
        migrations.AddConstraint(
            model_name='trainingbatchitem',
            constraint=models.UniqueConstraint(fields=('batch', 'question_version'), name='unique_training_question_per_batch'),
        ),
    ]
