# Generated by Django 5.1.15 on 2026-09-02 01:16

from django.db import migrations, models


def assign_training_ranks(apps, schema_editor):
    TrainingBatch = apps.get_model("assessments", "TrainingBatch")
    for batch in TrainingBatch.objects.order_by("scope_key", "batch_index", "created_at"):
        batch.free_access_rank = batch.batch_index
        batch.save(update_fields=["free_access_rank"])


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('assessments', '0006_mock_blueprint_versions'),
        ('curriculum', '0005_academicyear_studyenrollment_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingbatch',
            name='free_access_rank',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(assign_training_ranks, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='trainingbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('free_access_rank__isnull', False)), fields=('scope_key', 'free_access_rank'), name='unique_training_free_rank_per_scope'),
        ),
    ]
