# Generated by Django 5.1.15 on 2026-07-28 20:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_alter_unit_term'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activationcodeusage',
            options={'verbose_name': 'استخدام كود التفعيل', 'verbose_name_plural': 'استخدامات أكواد التفعيل'},
        ),
        migrations.AddField(
            model_name='activationcode',
            name='hash_version',
            field=models.CharField(choices=[('legacy_sha256', 'SHA-256 (قديم)'), ('hmac_sha256_v1', 'HMAC-SHA256 (v1)')], db_index=True, default='hmac_sha256_v1', max_length=30),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('expired', 'منتهي'), ('cancelled', 'ملغى'), ('revoked', 'مسحوب')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddConstraint(
            model_name='activationcodeusage',
            constraint=models.UniqueConstraint(fields=('activation_code', 'user'), name='unique_activation_code_usage_per_user'),
        ),
        migrations.AddConstraint(
            model_name='activationcodeusage',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('user', 'idempotency_key'), name='unique_activation_redemption_idempotency_per_user'),
        ),
    ]
