# Generated by Django 5.1.15 on 2026-09-02 01:16

import django.db.models.deletion
import hashlib
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_fe08_catalog(apps, schema_editor):
    AcademicYear = apps.get_model("curriculum", "AcademicYear")
    Subject = apps.get_model("curriculum", "Subject")
    Subscription = apps.get_model("subscriptions", "Subscription")
    Plan = apps.get_model("subscriptions", "SubscriptionPlan")
    Code = apps.get_model("subscriptions", "ActivationCode")
    Entitlement = apps.get_model("entitlements", "Entitlement")
    PlanEntitlement = apps.get_model("entitlements", "PlanEntitlement")
    year = AcademicYear.objects.filter(status="active").first()
    if year is None:
        return
    Subscription.objects.filter(academic_year__isnull=True).update(
        academic_year=year, expires_at=year.ends_at,
    )
    Subscription.objects.filter(source="activation_code").update(source="code")
    Code.objects.filter(status="active").update(status="available")
    Code.objects.filter(status="exhausted").update(status="redeemed")
    Code.objects.filter(status="disabled").update(status="revoked")

    contexts = Subject.objects.filter(status="published").values_list("grade_id", "section_id").distinct()
    prices = {1: 2000, 2: 3000, 3: 4000, 4: 5000, 5: 6000}
    arabic = {1: "مادة واحدة", 2: "مادتان", 3: "ثلاث مواد", 4: "أربع مواد", 5: "خمس مواد"}
    for grade_id, section_id in contexts:
        count = Subject.objects.filter(grade_id=grade_id, section_id=section_id, status="published").count()
        digest = hashlib.sha1(f"{year.pk}:{grade_id}:{section_id}".encode()).hexdigest()[:12]
        entitlement, _ = Entitlement.objects.get_or_create(
            code=f"FE08-SECTION-{digest}",
            defaults={
                "name": f"وصول كامل لمسار {section_id}",
                "entitlement_type": "full_access", "scope_type": "section",
                "grade_id": grade_id, "section_id": section_id, "is_active": True,
            },
        )
        for limit in range(1, min(5, count) + 1):
            plan, _ = Plan.objects.get_or_create(
                code=f"FE08-{digest}-{limit}",
                defaults={
                    "name": arabic[limit], "description": "وصول كامل للمواد المختارة حتى نهاية العام الدراسي",
                    "academic_year_id": year.pk, "grade_id": grade_id, "section_id": section_id,
                    "tier_type": "subject_count", "subject_limit": limit,
                    "duration_days": 365, "price": prices[limit], "currency": "YER",
                    "is_active": True, "is_catalog_visible": True, "sort_order": limit,
                    "starts_at": year.starts_at, "ends_at": year.ends_at,
                },
            )
            PlanEntitlement.objects.get_or_create(plan=plan, entitlement=entitlement)
        all_plan, _ = Plan.objects.get_or_create(
            code=f"FE08-{digest}-ALL",
            defaults={
                "name": "جميع المواد", "description": "وصول كامل تلقائي لكل مواد المسار حتى نهاية العام الدراسي",
                "academic_year_id": year.pk, "grade_id": grade_id, "section_id": section_id,
                "tier_type": "all_subjects", "subject_limit": None,
                "duration_days": 365, "price": 7000, "currency": "YER",
                "is_active": True, "is_catalog_visible": True, "sort_order": 6,
                "starts_at": year.starts_at, "ends_at": year.ends_at,
            },
        )
        PlanEntitlement.objects.get_or_create(plan=all_plan, entitlement=entitlement)


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0009_assessmentattempt_revision'),
        ('curriculum', '0005_academicyear_studyenrollment_academic_year'),
        ('entitlements', '0003_remove_freeaccesspolicy_unique_free_policy_per_subject_and_more'),
        ('question_bank', '0008_archive_unsupported_legacy_questions'),
        ('subscriptions', '0002_alter_activationcodeusage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationCodeBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_code', models.CharField(db_index=True, max_length=60, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subscriptions_activation_code_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FreeGenerationUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('custom', 'مخصص'), ('mock', 'محاكاة')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subscriptions_free_generation_uses',
            },
        ),
        migrations.CreateModel(
            name='GeneratedQuestionUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('custom', 'مخصص'), ('mock', 'محاكاة')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subscriptions_generated_question_uses',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('source', models.CharField(choices=[('code', 'رمز تفعيل'), ('admin', 'إدارة'), ('distributor', 'موزع'), ('google_play', 'Google Play (مستقبلي)'), ('yemeni_wallet', 'محفظة يمنية (مستقبلي)'), ('other_payment', 'دفع آخر (مستقبلي)')], max_length=50)),
                ('reason', models.TextField(blank=True, default='')),
                ('before_state', models.JSONField(blank=True, default=dict)),
                ('after_state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subscriptions_audit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='activationcode',
            options={'verbose_name': 'رمز التفعيل', 'verbose_name_plural': 'رموز التفعيل'},
        ),
        migrations.AlterModelOptions(
            name='activationcodeusage',
            options={'verbose_name': 'استخدام رمز التفعيل', 'verbose_name_plural': 'استخدامات رموز التفعيل'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['sort_order', 'subject_limit', 'code'], 'verbose_name': 'خطة الاشتراك', 'verbose_name_plural': 'خطط الاشتراكات'},
        ),
        migrations.RemoveConstraint(
            model_name='activationcodeusage',
            name='unique_activation_code_usage_per_user',
        ),
        migrations.AddField(
            model_name='subscription',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='curriculum.academicyear'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='commercial_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_all_subjects',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='selected_subjects',
            field=models.ManyToManyField(blank=True, related_name='selected_subscriptions', to='curriculum.subject'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_plans', to='curriculum.academicyear'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_plans', to='curriculum.grade'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_catalog_visible',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='offer_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='offer_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_plans', to='curriculum.section'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='subject_limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='tier_type',
            field=models.CharField(choices=[('subject_count', 'عدد مواد'), ('all_subjects', 'جميع المواد')], db_index=True, default='subject_count', max_length=20),
        ),
        migrations.AlterField(
            model_name='activationcode',
            name='status',
            field=models.CharField(choices=[('available', 'متاح'), ('redeemed', 'مستخدم'), ('expired', 'منتهي'), ('revoked', 'ملغى'), ('active', 'متاح (قديم)'), ('exhausted', 'مستخدم (قديم)'), ('disabled', 'ملغى (قديم)')], db_index=True, default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='source',
            field=models.CharField(choices=[('code', 'رمز تفعيل'), ('admin', 'إدارة'), ('distributor', 'موزع'), ('google_play', 'Google Play (مستقبلي)'), ('yemeni_wallet', 'محفظة يمنية (مستقبلي)'), ('other_payment', 'دفع آخر (مستقبلي)')], default='code', max_length=50),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'academic_year', 'status'], name='sub_user_year_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='activationcodeusage',
            constraint=models.UniqueConstraint(fields=('activation_code',), name='unique_single_activation_code_usage'),
        ),
        migrations.AddField(
            model_name='activationcodebatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activationcodebatch',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='code_batches', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='activationcode',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='codes', to='subscriptions.activationcodebatch'),
        ),
        migrations.AddField(
            model_name='freegenerationuse',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='curriculum.academicyear'),
        ),
        migrations.AddField(
            model_name='freegenerationuse',
            name='attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='free_generation_use', to='attempts.assessmentattempt'),
        ),
        migrations.AddField(
            model_name='freegenerationuse',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculum.subject'),
        ),
        migrations.AddField(
            model_name='freegenerationuse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_generation_uses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatedquestionuse',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='curriculum.academicyear'),
        ),
        migrations.AddField(
            model_name='generatedquestionuse',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_uses', to='attempts.assessmentattempt'),
        ),
        migrations.AddField(
            model_name='generatedquestionuse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_uses', to='question_bank.question'),
        ),
        migrations.AddField(
            model_name='generatedquestionuse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_question_uses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionaudit',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionaudit',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='subscriptions.subscription'),
        ),
        migrations.AddIndex(
            model_name='freegenerationuse',
            index=models.Index(fields=['user', 'academic_year', 'subject', 'mode'], name='free_gen_use_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedquestionuse',
            index=models.Index(fields=['user', 'academic_year', 'mode', 'question'], name='gen_use_pool_idx'),
        ),
        migrations.AddConstraint(
            model_name='generatedquestionuse',
            constraint=models.UniqueConstraint(fields=('user', 'academic_year', 'question', 'mode'), name='unique_generated_question_use'),
        ),
        migrations.RunPython(seed_fe08_catalog, migrations.RunPython.noop),
    ]
