# Generated by Django 5.1.15 on 2026-09-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_activationcodebatch_freegenerationuse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='source',
            field=models.CharField(choices=[('code', 'رمز تفعيل'), ('admin', 'إدارة'), ('distributor', 'موزع'), ('legacy_guest', 'اشتراك زائر قديم'), ('google_play', 'Google Play (مستقبلي)'), ('yemeni_wallet', 'محفظة يمنية (مستقبلي)'), ('other_payment', 'دفع آخر (مستقبلي)')], default='code', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriptionaudit',
            name='source',
            field=models.CharField(choices=[('code', 'رمز تفعيل'), ('admin', 'إدارة'), ('distributor', 'موزع'), ('legacy_guest', 'اشتراك زائر قديم'), ('google_play', 'Google Play (مستقبلي)'), ('yemeni_wallet', 'محفظة يمنية (مستقبلي)'), ('other_payment', 'دفع آخر (مستقبلي)')], max_length=50),
        ),
    ]
