# Generated by Django 5.1.15 on 2026-09-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_preserve_legacy_subscription_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activationcodebatch',
            options={'ordering': ['-created_at'], 'permissions': [('generate_code_batch', 'Can generate activation code batches')], 'verbose_name': 'دفعة رموز التفعيل', 'verbose_name_plural': 'دفعات رموز التفعيل'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'permissions': [('direct_activate_subscription', 'Can directly activate student subscriptions')], 'verbose_name': 'اشتراك الطالب', 'verbose_name_plural': 'اشتراكات الطلاب'},
        ),
    ]
