# Generated by Django 5.1.15 on 2026-07-24 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'محافظة',
                'verbose_name_plural': 'المحافظات',
                'db_table': 'locations_governorate',
                'ordering': ['sort_order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='locations.governorate')),
            ],
            options={
                'verbose_name': 'مديرية',
                'verbose_name_plural': 'المديريات',
                'db_table': 'locations_district',
                'ordering': ['sort_order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Isolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isolations', to='locations.district')),
            ],
            options={
                'verbose_name': 'عزلة',
                'verbose_name_plural': 'العزل',
                'db_table': 'locations_isolation',
                'ordering': ['sort_order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('school_type', models.CharField(choices=[('public', 'حكومي'), ('private', 'خاص')], default='public', max_length=10)),
                ('gender_type', models.CharField(choices=[('boys', 'بنين'), ('girls', 'بنات'), ('mixed', 'مختلط')], default='mixed', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='locations.district')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='locations.governorate')),
                ('isolation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='locations.isolation')),
            ],
            options={
                'verbose_name': 'مدرسة',
                'verbose_name_plural': 'المدارس',
                'db_table': 'locations_school',
                'ordering': ['name_ar'],
            },
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('governorate', 'code'), name='unique_governorate_district_code'),
        ),
        migrations.AddConstraint(
            model_name='isolation',
            constraint=models.UniqueConstraint(fields=('district', 'code'), name='unique_district_isolation_code'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['governorate', 'district', 'isolation'], name='locations_s_governo_b93a1d_idx'),
        ),
    ]
