# Generated by Django 5.1.15 on 2026-07-27 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='locations.governorate'),
        ),
        migrations.AlterField(
            model_name='isolation',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='isolations', to='locations.district'),
        ),
        migrations.AlterField(
            model_name='school',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='locations.district'),
        ),
        migrations.AlterField(
            model_name='school',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='locations.governorate'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['name_ar'], name='locations_s_name_ar_674cc0_idx'),
        ),
    ]
