# Generated by Django 5.1.15 on 2026-07-26 18:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('request_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('locked', 'قيد التشغيل'), ('completed', 'مكتمل'), ('failed', 'فاشل')], db_index=True, default='locked', max_length=20)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل الإديمبوتنسي',
                'verbose_name_plural': 'سجلات الإديمبوتنسي',
                'db_table': 'common_idempotency_records',
            },
        ),
    ]
