# Generated by Django 5.1.15 on 2026-07-27 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='idempotencyrecord',
            name='actor_scope',
            field=models.CharField(db_index=True, default='anon', max_length=255),
        ),
        migrations.AddField(
            model_name='idempotencyrecord',
            name='method',
            field=models.CharField(default='POST', max_length=10),
        ),
        migrations.AlterField(
            model_name='idempotencyrecord',
            name='key',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='idempotencyrecord',
            name='status',
            field=models.CharField(choices=[('processing', 'قيد المعالجة'), ('completed', 'مكتمل'), ('failed', 'فاشل')], db_index=True, default='processing', max_length=20),
        ),
        migrations.AddIndex(
            model_name='idempotencyrecord',
            index=models.Index(fields=['expires_at', 'status'], name='idx_idem_expires_status'),
        ),
        migrations.AddConstraint(
            model_name='idempotencyrecord',
            constraint=models.UniqueConstraint(fields=('actor_scope', 'endpoint', 'key'), name='unique_actor_endpoint_idempotency_key'),
        ),
    ]
