# Generated by Django 5.1.15 on 2026-07-26 18:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('ministerial', 'وزاري'), ('training', 'تدريبي'), ('self_practice', 'اختبر نفسك'), ('custom', 'مخصص'), ('teacher_created', 'إنشاء معلم'), ('ai_generated', 'ذكاء اصطناعي')], db_index=True, default='ministerial', max_length=30)),
                ('question_type', models.CharField(choices=[('multiple_choice', 'اختيار من متعدد'), ('true_false', 'صواب / خطأ'), ('multiple_select', 'اختيارات متعددة'), ('short_answer', 'إجابة قصيرة'), ('matching', 'مطابقة'), ('ordering', 'ترتيب'), ('numeric', 'رقمي'), ('essay', 'مقالي'), ('interactive', 'تفاعلي')], db_index=True, default='multiple_choice', max_length=30)),
                ('difficulty', models.CharField(choices=[('easy', 'سهل'), ('medium', 'متوسط'), ('hard', 'صعب')], db_index=True, default='medium', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('under_review', 'قيد المراجعة'), ('approved', 'معتمد'), ('published', 'منشور'), ('archived', 'مؤرشف')], db_index=True, default='published', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='curriculum.lesson')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_questions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='curriculum.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='curriculum.topic')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='curriculum.unit')),
            ],
            options={
                'verbose_name': 'السؤال',
                'verbose_name_plural': 'بنك الأسئلة',
                'db_table': 'question_bank_questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pool_type', models.CharField(default='unit', max_length=30)),
                ('source_filter', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('under_review', 'قيد المراجعة'), ('approved', 'معتمد'), ('published', 'منشور'), ('archived', 'مؤرشف')], default='published', max_length=20)),
                ('question_count', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.lesson')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.subject')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.unit')),
            ],
            options={
                'db_table': 'question_bank_pools',
            },
        ),
        migrations.CreateModel(
            name='QuestionPoolStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(blank=True, choices=[('ministerial', 'وزاري'), ('training', 'تدريبي'), ('self_practice', 'اختبر نفسك'), ('custom', 'مخصص'), ('teacher_created', 'إنشاء معلم'), ('ai_generated', 'ذكاء اصطناعي')], max_length=30, null=True)),
                ('question_type', models.CharField(blank=True, choices=[('multiple_choice', 'اختيار من متعدد'), ('true_false', 'صواب / خطأ'), ('multiple_select', 'اختيارات متعددة'), ('short_answer', 'إجابة قصيرة'), ('matching', 'مطابقة'), ('ordering', 'ترتيب'), ('numeric', 'رقمي'), ('essay', 'مقالي'), ('interactive', 'تفاعلي')], max_length=30, null=True)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'سهل'), ('medium', 'متوسط'), ('hard', 'صعب')], max_length=20, null=True)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('published_questions', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.lesson')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.subject')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.unit')),
            ],
            options={
                'db_table': 'question_bank_pool_stats',
            },
        ),
        migrations.CreateModel(
            name='QuestionStimulus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stimulus_type', models.CharField(choices=[('reading_passage', 'قطعة قراءة'), ('shared_image', 'صورة مشتركة'), ('formula_sheet', 'قوانين وصيغ'), ('instructions', 'تعليمات'), ('table', 'جدول'), ('diagram', 'رسم بياني'), ('reference_text', 'نص مرجعي'), ('other', 'آخر')], db_index=True, default='reading_passage', max_length=30)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='question_stimuli/')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='question_stimuli/files/')),
                ('layout', models.CharField(choices=[('text_only', 'نص فقط'), ('image_only', 'صورة فقط'), ('text_then_image', 'نص ثم صورة'), ('image_then_text', 'صورة ثم نص'), ('side_by_side', 'جنباً إلى جنب')], default='text_only', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('under_review', 'قيد المراجعة'), ('approved', 'معتمد'), ('published', 'منشور'), ('archived', 'مؤرشف')], db_index=True, default='published', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stimuli', to='curriculum.lesson')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stimuli', to='curriculum.subject')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stimuli', to='curriculum.unit')),
            ],
            options={
                'verbose_name': 'المحتوى المشترك (Stimulus)',
                'verbose_name_plural': 'القطع والنصوص المشتركة',
                'db_table': 'question_bank_stimuli',
            },
        ),
        migrations.CreateModel(
            name='QuestionVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('question_text', models.TextField(blank=True, null=True)),
                ('prompt_layout', models.CharField(choices=[('text_only', 'نص فقط'), ('image_only', 'صورة فقط'), ('text_then_image', 'نص ثم صورة'), ('image_then_text', 'صورة ثم نص'), ('side_by_side', 'جنباً إلى جنب')], default='text_only', max_length=30)),
                ('short_explanation', models.TextField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('points', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='question_bank.question')),
            ],
            options={
                'verbose_name': 'نسخة السؤال',
                'verbose_name_plural': 'نسخ الأسئلة',
                'db_table': 'question_bank_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='QuestionPoolItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('ministerial', 'وزاري'), ('training', 'تدريبي'), ('self_practice', 'اختبر نفسك'), ('custom', 'مخصص'), ('teacher_created', 'إنشاء معلم'), ('ai_generated', 'ذكاء اصطناعي')], max_length=30)),
                ('difficulty', models.CharField(choices=[('easy', 'سهل'), ('medium', 'متوسط'), ('hard', 'صعب')], max_length=20)),
                ('sort_key', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='question_bank.questionpool')),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_bank.questionversion')),
            ],
            options={
                'db_table': 'question_bank_pool_items',
                'ordering': ['sort_key'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_key', models.CharField(help_text='A, B, C, D', max_length=10)),
                ('option_text', models.TextField(blank=True, null=True)),
                ('option_image_path', models.ImageField(blank=True, null=True, upload_to='question_options/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='question_bank.questionversion')),
            ],
            options={
                'verbose_name': 'خيار السؤال',
                'verbose_name_plural': 'خيارات السؤال',
                'db_table': 'question_bank_options',
                'ordering': ['sort_order', 'option_key'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(default='image', max_length=20)),
                ('asset_role', models.CharField(choices=[('question_stem', 'نص / صورة السؤال'), ('supporting_diagram', 'رسم توضيحي'), ('table', 'جدول'), ('equation', 'معادلة'), ('explanation', 'الشرح والتوضيح'), ('other', 'آخر')], default='question_stem', max_length=30)),
                ('file_path', models.FileField(upload_to='questions/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='question_bank.questionversion')),
            ],
            options={
                'verbose_name': 'ملحق السؤال',
                'verbose_name_plural': 'ملحقات وصور الأسئلة',
                'db_table': 'question_bank_assets',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='question_bank.questionversion'),
        ),
        migrations.CreateModel(
            name='QuestionStimulusLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stimulus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='question_bank.questionstimulus')),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stimulus_links', to='question_bank.questionversion')),
            ],
            options={
                'db_table': 'question_bank_stimulus_links',
                'ordering': ['sort_order'],
                'unique_together': {('stimulus', 'question_version')},
            },
        ),
    ]
