# Generated by Django 5.1.15 on 2026-07-27 20:55

from django.conf import settings
from django.db import migrations, models


def fix_duplicate_option_orders(apps, schema_editor):
    QuestionOption = apps.get_model("question_bank", "QuestionOption")
    QuestionVersion = apps.get_model("question_bank", "QuestionVersion")
    for q_version in QuestionVersion.objects.all():
        options = list(QuestionOption.objects.filter(question_version=q_version).order_by("sort_order", "option_key", "id"))
        for idx, option in enumerate(options, start=1):
            if option.sort_order != idx:
                option.sort_order = idx
                option.save(update_fields=["sort_order"])


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0002_alter_question_lesson_alter_question_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(fix_duplicate_option_orders, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='questionasset',
            constraint=models.UniqueConstraint(fields=('question_version', 'sort_order'), name='unique_question_asset_order'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question_version', 'option_key'), name='unique_option_key_per_question_version'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question_version', 'sort_order'), name='unique_option_order_per_question_version'),
        ),
        migrations.AddConstraint(
            model_name='questionversion',
            constraint=models.UniqueConstraint(fields=('question', 'version_number'), name='unique_question_version_number'),
        ),
        migrations.AddConstraint(
            model_name='questionversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('question',), name='unique_current_version_per_question'),
        ),
    ]
