# Generated by Django 5.1.15 on 2026-08-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0004_questionversion_answer_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='بيانات المنشأ والتتبع غير الوزارية؛ لا تُستخدم بدل العلاقات الأكاديمية.'),
        ),
    ]
