# Generated by Django 5.1.15 on 2026-08-25 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_lifecycle_audit(apps, schema_editor):
    Question = apps.get_model('question_bank', 'Question')
    QuestionVersion = apps.get_model('question_bank', 'QuestionVersion')
    QuestionVersion.objects.filter(published_at__isnull=False).update(status='published')
    for question in Question.objects.filter(status='published').iterator(chunk_size=500):
        published_at = (
            QuestionVersion.objects.filter(question_id=question.pk, published_at__isnull=False)
            .order_by('-version_number')
            .values_list('published_at', flat=True)
            .first()
        )
        Question.objects.filter(pk=question.pk).update(
            published_at=published_at,
            approved_at=question.approved_at or published_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_normalize_scoped_term_ids'),
        ('question_bank', '0005_question_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at'], 'permissions': [('review_question', 'Can review question versions'), ('publish_question', 'Can publish question versions'), ('retire_question', 'Can retire questions')], 'verbose_name': 'السؤال', 'verbose_name_plural': 'بنك الأسئلة'},
        ),
        migrations.AddField(
            model_name='question',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='retired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionversion',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionversion',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_question_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionversion',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_question_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionversion',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionversion',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_question_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionversion',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('under_review', 'قيد المراجعة'), ('approved', 'معتمد'), ('published', 'منشور'), ('archived', 'مؤرشف')], db_index=True, default='published', max_length=20),
        ),
        migrations.RunPython(backfill_lifecycle_audit, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject', 'status', 'source_type', 'difficulty', 'question_type'], name='qb_q_pool_health_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['unit', 'status', 'source_type'], name='qb_q_unit_pool_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['lesson', 'status', 'source_type'], name='qb_q_lesson_pool_idx'),
        ),
    ]
