# Generated by Django 5.1.15 on 2026-07-26 18:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPerformanceInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('strength', 'نقطة قوة'), ('weakness', 'نقطة ضعف'), ('needs_review', 'يحتاج مراجعة'), ('improving', 'في تحسن')], db_index=True, default='strength', max_length=20)),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('evidence_count', models.PositiveIntegerField(default=1)),
                ('message', models.TextField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.lesson')),
                ('study_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.studyenrollment')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.subject')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تحليل أداء الطالب',
                'verbose_name_plural': 'تحليلات أداء الطلاب',
                'db_table': 'analytics_student_insights',
                'ordering': ['-calculated_at'],
            },
        ),
    ]
