# Generated by Django 5.1.15 on 2026-07-28 22:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('attempts', '0002_alter_attemptanswer_unique_together_and_more'),
        ('curriculum', '0003_alter_unit_term'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentperformanceinsight',
            name='calculation_version',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(db_index=True, max_length=255)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('schema_version', models.CharField(default='1.0', max_length=10)),
                ('source_type', models.CharField(blank=True, default='', max_length=50)),
                ('source_id', models.CharField(blank=True, default='', max_length=200)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attempts.assessmentattempt')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.lesson')),
                ('study_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.studyenrollment')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.subject')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'حدث تحليلي',
                'verbose_name_plural': 'أحداث تحليلية',
                'db_table': 'analytics_events',
                'constraints': [models.UniqueConstraint(fields=('event_id',), name='unique_analytics_event_id'), models.UniqueConstraint(condition=models.Q(('attempt__isnull', False), ('event_type', 'assessment_submitted')), fields=('event_type', 'attempt'), name='unique_assessment_submitted_event_per_attempt')],
            },
        ),
        migrations.CreateModel(
            name='DailyLearningSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('learning_seconds', models.PositiveIntegerField(default=0)),
                ('resources_started', models.PositiveIntegerField(default=0)),
                ('resources_completed', models.PositiveIntegerField(default=0)),
                ('attempts_submitted', models.PositiveIntegerField(default=0)),
                ('questions_answered', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('points_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('points_possible', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.studyenrollment')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_learning_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملخص التعلم اليومي',
                'verbose_name_plural': 'ملخصات التعلم اليومية',
                'db_table': 'analytics_daily_summaries',
                'constraints': [models.UniqueConstraint(fields=('user', 'study_enrollment', 'date', 'subject'), name='unique_daily_summary_per_enrollment')],
            },
        ),
    ]
