# Generated by Django 5.1.15 on 2026-07-28 23:53

from django.conf import settings
from django.db import migrations, models


def merge_duplicate_daily_summaries(apps, schema_editor):
    DailyLearningSummary = apps.get_model("analytics", "DailyLearningSummary")
    from django.db.models import Count

    dups_overall = (
        DailyLearningSummary.objects.filter(subject__isnull=True)
        .values("user_id", "study_enrollment_id", "date")
        .annotate(cnt=Count("id"))
        .filter(cnt__gt=1)
    )
    for item in dups_overall:
        records = list(
            DailyLearningSummary.objects.filter(
                user_id=item["user_id"],
                study_enrollment_id=item["study_enrollment_id"],
                date=item["date"],
                subject__isnull=True,
            ).order_by("id")
        )
        if len(records) > 1:
            primary = records[0]
            for extra in records[1:]:
                primary.learning_seconds += extra.learning_seconds
                primary.resources_started += extra.resources_started
                primary.resources_completed += extra.resources_completed
                primary.attempts_submitted += extra.attempts_submitted
                primary.questions_answered += extra.questions_answered
                primary.correct_answers += extra.correct_answers
                primary.points_earned += extra.points_earned
                primary.points_possible += extra.points_possible
                extra.delete()
            primary.save()

    dups_subject = (
        DailyLearningSummary.objects.filter(subject__isnull=False)
        .values("user_id", "study_enrollment_id", "date", "subject_id")
        .annotate(cnt=Count("id"))
        .filter(cnt__gt=1)
    )
    for item in dups_subject:
        records = list(
            DailyLearningSummary.objects.filter(
                user_id=item["user_id"],
                study_enrollment_id=item["study_enrollment_id"],
                date=item["date"],
                subject_id=item["subject_id"],
            ).order_by("id")
        )
        if len(records) > 1:
            primary = records[0]
            for extra in records[1:]:
                primary.learning_seconds += extra.learning_seconds
                primary.resources_started += extra.resources_started
                primary.resources_completed += extra.resources_completed
                primary.attempts_submitted += extra.attempts_submitted
                primary.questions_answered += extra.questions_answered
                primary.correct_answers += extra.correct_answers
                primary.points_earned += extra.points_earned
                primary.points_possible += extra.points_possible
                extra.delete()
            primary.save()


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_studentperformanceinsight_calculation_version_and_more'),
        ('curriculum', '0003_alter_unit_term'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailylearningsummary',
            name='unique_daily_summary_per_enrollment',
        ),
        migrations.RunPython(merge_duplicate_daily_summaries, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='dailylearningsummary',
            constraint=models.UniqueConstraint(condition=models.Q(('subject__isnull', False)), fields=('user', 'study_enrollment', 'date', 'subject'), name='unique_daily_subject_summary'),
        ),
        migrations.AddConstraint(
            model_name='dailylearningsummary',
            constraint=models.UniqueConstraint(condition=models.Q(('subject__isnull', True)), fields=('user', 'study_enrollment', 'date'), name='unique_daily_overall_summary'),
        ),
    ]

