# Generated by Django 5.1.15 on 2026-08-24 23:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_remove_dailylearningsummary_unique_daily_summary_per_enrollment_and_more'),
        ('attempts', '0008_question_performance_evidence'),
        ('curriculum', '0004_normalize_scoped_term_ids'),
        ('ministerial_exams', '0004_lesson_ministerial_batches'),
        ('question_bank', '0005_question_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionQualityAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity_key', models.CharField(max_length=180, unique=True)),
                ('source_type', models.CharField(db_index=True, max_length=30)),
                ('difficulty', models.CharField(db_index=True, max_length=20)),
                ('question_type', models.CharField(db_index=True, max_length=30)),
                ('presented_count', models.PositiveIntegerField(default=0)),
                ('answered_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('incorrect_count', models.PositiveIntegerField(default=0)),
                ('partial_count', models.PositiveIntegerField(default=0)),
                ('unanswered_count', models.PositiveIntegerField(default=0)),
                ('pending_count', models.PositiveIntegerField(default=0)),
                ('earned_points', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('maximum_gradable_points', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('response_time_total_seconds', models.PositiveBigIntegerField(default=0)),
                ('response_time_sample_count', models.PositiveIntegerField(default=0)),
                ('option_distribution', models.JSONField(blank=True, default=dict)),
                ('sample_size', models.PositiveIntegerField(default=0)),
                ('sample_state', models.CharField(db_index=True, default='insufficient', max_length=20)),
                ('quality_flags', models.JSONField(blank=True, default=list)),
                ('first_finalized_at', models.DateTimeField(blank=True, null=True)),
                ('last_finalized_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='curriculum.lesson')),
                ('ministerial_exam_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_aggregates', to='ministerial_exams.ministerialexamitem')),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_aggregates', to='question_bank.questionversion')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculum.subject')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='curriculum.unit')),
            ],
            options={
                'db_table': 'analytics_question_quality_aggregates',
                'indexes': [models.Index(fields=['subject', 'source_type', 'sample_state'], name='an_qa_subject_sample_idx'), models.Index(fields=['unit', 'difficulty', 'question_type'], name='an_qa_unit_meta_idx'), models.Index(fields=['lesson', 'sample_state'], name='an_qa_lesson_sample_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuestionQualityContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity_key', models.CharField(db_index=True, max_length=180)),
                ('source_type', models.CharField(db_index=True, max_length=30)),
                ('difficulty', models.CharField(db_index=True, max_length=20)),
                ('question_type', models.CharField(db_index=True, max_length=30)),
                ('assessment_kind', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('attempt_type', models.CharField(db_index=True, max_length=30)),
                ('is_remediation', models.BooleanField(db_index=True, default=False)),
                ('outcome', models.CharField(db_index=True, max_length=20)),
                ('was_answered', models.BooleanField(default=False)),
                ('awarded_points', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('maximum_gradable_points', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('response_time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('selected_option_key', models.CharField(blank=True, max_length=20, null=True)),
                ('option_keys_snapshot', models.JSONField(blank=True, default=list)),
                ('correct_option_keys_snapshot', models.JSONField(blank=True, default=list)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_contribution', to='attempts.attemptquestion')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='curriculum.lesson')),
                ('ministerial_exam_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_contributions', to='ministerial_exams.ministerialexamitem')),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_contributions', to='question_bank.questionversion')),
                ('study_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_quality_contributions', to='curriculum.studyenrollment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculum.subject')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='curriculum.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_quality_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_question_quality_contributions',
                'indexes': [models.Index(fields=['user', 'study_enrollment', 'is_remediation', 'subject'], name='an_qc_student_subject_idx'), models.Index(fields=['user', 'study_enrollment', 'unit'], name='an_qc_student_unit_idx'), models.Index(fields=['user', 'study_enrollment', 'lesson'], name='an_qc_student_lesson_idx')],
            },
        ),
    ]
