"""
User Device Model.

Tracks physical devices linked to a user account.
Uses installation_id generated by the Flutter app (not IMEI).
"""

import uuid

from django.conf import settings
from django.db import models


class UserDevice(models.Model):
    """
    Represents a physical device linked to a user.

    - installation_id is generated by Flutter on first launch.
    - A user can have multiple devices.
    - Same device cannot be registered twice for the same user.
    """

    class Platform(models.TextChoices):
        ANDROID = "android", "Android"
        IOS = "ios", "iOS"
        WEB = "web", "Web"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="devices",
    )
    installation_id = models.CharField(
        max_length=255,
        db_index=True,
        help_text="Unique device identifier generated by Flutter.",
    )
    platform = models.CharField(
        max_length=10,
        choices=Platform.choices,
        default=Platform.ANDROID,
    )
    device_name = models.CharField(max_length=255, blank=True, default="")
    operating_system = models.CharField(max_length=100, blank=True, default="")
    app_version = models.CharField(max_length=20, blank=True, default="")
    push_token = models.TextField(null=True, blank=True)
    first_seen_at = models.DateTimeField(auto_now_add=True)
    last_seen_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True, db_index=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "accounts_user_device"
        ordering = ["-last_seen_at"]
        verbose_name = "جهاز المستخدم"
        verbose_name_plural = "أجهزة المستخدمين"
        constraints = [
            models.UniqueConstraint(
                fields=["user", "installation_id"],
                name="unique_user_installation",
            ),
        ]

    def __str__(self):
        return f"{self.device_name or self.installation_id[:8]} ({self.get_platform_display()}) — {self.user}"
