# Generated by Django 5.1.15 on 2026-09-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentimportlog',
            options={'ordering': ['-created_at'], 'permissions': [('execute_import', 'Can execute validated content imports')], 'verbose_name': 'سجل استيراد المحتوى', 'verbose_name_plural': 'سجلات استيراد المحتوى'},
        ),
    ]
