# Generated by Django 5.1.15 on 2026-09-06 02:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_studentprofile_custom_locations'),
        ('curriculum', '0007_dashboardbanner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('SYSTEM', 'إعلانات المنصة'), ('CONTENT', 'المحتوى'), ('LEARNING', 'التعلم'), ('ASSESSMENT', 'الاختبارات والمراجعة'), ('SUBSCRIPTION', 'الاشتراك'), ('ACCOUNT', 'الحساب والأمان')], max_length=20)),
                ('source', models.CharField(choices=[('ADMIN', 'إدارة'), ('SYSTEM', 'نظام')], default='ADMIN', max_length=10)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(max_length=2000)),
                ('priority', models.CharField(choices=[('LOW', 'منخفض'), ('NORMAL', 'عادي'), ('HIGH', 'مرتفع')], default='NORMAL', max_length=10)),
                ('action_type', models.CharField(choices=[('NONE', 'رسالة فقط'), ('OPEN_SUBJECT', 'مادة'), ('OPEN_UNIT', 'وحدة'), ('OPEN_LESSON', 'درس'), ('OPEN_RESOURCE', 'ملخص'), ('OPEN_SMART_CARDS', 'بطاقات ذكية'), ('OPEN_ATTEMPT', 'استئناف محاولة'), ('OPEN_RESULT', 'نتيجة محاولة'), ('OPEN_SUBSCRIPTION', 'الاشتراك'), ('OPEN_SETTINGS', 'الإعدادات')], default='NONE', max_length=30)),
                ('action_payload', models.JSONField(blank=True, default=dict)),
                ('push_enabled', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SCHEDULED', 'مجدول'), ('PUBLISHING', 'تجهيز المستلمين'), ('PUBLISHED', 'منشور'), ('CANCELLED', 'ملغى'), ('EXPIRED', 'منتهي')], default='DRAFT', max_length=20)),
                ('audience', models.CharField(blank=True, choices=[('EVERYONE', 'جميع المستخدمين والزوار النشطين'), ('REGISTERED', 'المستخدمون المسجلون'), ('GUESTS', 'الزوار'), ('GRADE', 'صف دراسي'), ('SECTION', 'صف ومسار'), ('SUBJECT', 'طلاب المادة'), ('USERS', 'مستخدمون محددون')], default='', max_length=20)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('dedupe_key', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('audience_cursor', models.UUIDField(editable=False, null=True)),
                ('audience_cutoff', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_notifications', to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='curriculum.grade')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='curriculum.section')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='curriculum.subject')),
                ('users', models.ManyToManyField(blank=True, related_name='targeted_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_content', models.BooleanField(default=True)),
                ('assessment', models.BooleanField(default=True)),
                ('subscription', models.BooleanField(default=True)),
                ('announcements', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_inbox', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_id', models.CharField(editable=False, max_length=255, unique=True)),
                ('token', models.CharField(max_length=1024, unique=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('token_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_binding', to='accounts.userdevice')),
            ],
        ),
        migrations.CreateModel(
            name='PushDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SENT', 'SENT'), ('FAILED', 'FAILED'), ('SKIPPED', 'SKIPPED')], default='PENDING', max_length=10)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(null=True)),
                ('failed_at', models.DateTimeField(null=True)),
                ('error_code', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notificationrecipient')),
                ('push_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.pushdevice')),
            ],
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'publish_at'], name='notificatio_status_8a2cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrecipient',
            index=models.Index(fields=['user', 'read_at'], name='notificatio_user_id_b9cd65_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrecipient',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_b99848_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationrecipient',
            constraint=models.UniqueConstraint(fields=('notification', 'user'), name='nt_unique_recipient'),
        ),
        migrations.AddIndex(
            model_name='pushdelivery',
            index=models.Index(fields=['status', 'next_attempt_at'], name='notificatio_status_a38fee_idx'),
        ),
        migrations.AddConstraint(
            model_name='pushdelivery',
            constraint=models.UniqueConstraint(fields=('recipient', 'push_device'), name='nt_unique_delivery'),
        ),
    ]
