# Generated by Django 5.1.15 on 2026-09-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='audience',
            field=models.CharField(blank=True, choices=[('EVERYONE', 'جميع المستخدمين والزوار النشطين'), ('REGISTERED', 'المستخدمون المسجلون'), ('GUESTS', 'الزوار'), ('GRADE', 'صف دراسي'), ('SECTION', 'صف ومسار'), ('SUBJECT', 'طلاب المادة'), ('SUBJECT_ACCESS', 'طلاب لديهم وصول كامل للمادة'), ('USERS', 'مستخدمون محددون')], default='', max_length=20),
        ),
    ]
