# Generated by Django 5.1.15 on 2026-09-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_audience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'permissions': [('publish_notification', 'Can publish and schedule notifications')], 'verbose_name': 'إشعار', 'verbose_name_plural': 'الإشعارات'},
        ),
    ]
